/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * admin.java
 *
 * Created on Jun 16, 2016, 11:58:42 PM
 */
package dispenda;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Agung
 */
public class admin extends javax.swing.JFrame {
Connection c;
    ResultSet r;
    Statement s;
    private Statement cn;
    private Connection conn;
    /** Creates new form admin */
    public admin() {
        initComponents();
        bersih();
        tampildata(); 
        lebarKolom();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        al = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_admin = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        del = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        save = new javax.swing.JButton();
        can = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N

        jDesktopPane4.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Alamat");
        jLabel1.setBounds(20, 160, 100, 14);
        jDesktopPane4.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Password");
        jLabel3.setBounds(20, 80, 80, 14);
        jDesktopPane4.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Nama Lengkap");
        jLabel4.setBounds(20, 120, 100, 10);
        jDesktopPane4.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        user.setBounds(140, 40, 210, 20);
        jDesktopPane4.add(user, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nama.setBounds(140, 120, 210, 20);
        jDesktopPane4.add(nama, javax.swing.JLayeredPane.DEFAULT_LAYER);

        al.setColumns(20);
        al.setRows(5);
        jScrollPane1.setViewportView(al);

        jScrollPane1.setBounds(140, 170, 210, 80);
        jDesktopPane4.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Username");
        jLabel5.setBounds(20, 40, 80, 15);
        jDesktopPane4.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pas.setBounds(140, 80, 210, 20);
        jDesktopPane4.add(pas, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBounds(20, 10, 390, 280);
        jDesktopPane3.add(jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane5.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        t_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_adminMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(t_admin);

        jScrollPane2.setBounds(20, 40, 450, 200);
        jDesktopPane5.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("DATA ADMIN");
        jLabel6.setBounds(200, 10, 120, 20);
        jDesktopPane5.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane5.setBounds(430, 100, 490, 270);
        jDesktopPane3.add(jDesktopPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane6.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        del.setBackground(new java.awt.Color(0, 0, 102));
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/del.png"))); // NOI18N
        del.setBorderPainted(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        del.setBounds(110, 10, 60, 60);
        jDesktopPane6.add(del, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/edit.png"))); // NOI18N
        edit.setBorderPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        edit.setBounds(20, 10, 60, 60);
        jDesktopPane6.add(edit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane6.setBounds(580, 10, 190, 80);
        jDesktopPane3.add(jDesktopPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane7.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/save.png"))); // NOI18N
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.setBounds(20, 10, 50, 50);
        jDesktopPane7.add(save, javax.swing.JLayeredPane.DEFAULT_LAYER);

        can.setBackground(new java.awt.Color(0, 0, 102));
        can.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/cancel.png"))); // NOI18N
        can.setBorderPainted(false);
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        can.setBounds(90, 10, 60, 50);
        jDesktopPane7.add(can, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane7.setBounds(110, 300, 170, 70);
        jDesktopPane3.add(jDesktopPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(10, 100, 940, 390);
        jDesktopPane1.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        home.setBackground(new java.awt.Color(0, 0, 102));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/h1.png"))); // NOI18N
        home.setBorderPainted(false);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        home.setBounds(440, 500, 113, 30);
        jDesktopPane1.add(home, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N
        jLabel2.setBounds(2, 4, 962, 90);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void lebarKolom(){ 
        TableColumn column;
        t_admin.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = t_admin.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = t_admin.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = t_admin.getColumnModel().getColumn(2); 
        column.setPreferredWidth(200); 
        column = t_admin.getColumnModel().getColumn(3); 
        column.setPreferredWidth(200);
    }
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void t_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_adminMouseClicked
        // TODO add your handling code here:
                int table = t_admin.getSelectedRow();
//mengambil data dari table
String a = t_admin.getValueAt(table, 0).toString();
String b = t_admin.getValueAt(table, 1).toString();
String c = t_admin.getValueAt(table, 2).toString();
String d = t_admin.getValueAt(table, 3).toString();


user.setText(a);
pas.setText(b);
nama.setText(c);
al.setText(d);
    }//GEN-LAST:event_t_adminMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            
            koneksi();
            String sql = "insert into tb_admin values ('"+ user.getText()+"','"+ pas.getText()+"','" + nama.getText() +"','" + al.getText() +"')";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_admin set password='" + pas.getText() + "'," +
                    " nama='" + nama.getText() + "'," +
                    " alamat='" + al.getText() + "'" +
                    " where username='" + user.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());} 
    }//GEN-LAST:event_editActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
         try{
            koneksi();
            String sql = "delete from tb_admin where username='"+ user.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_delActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        // TODO add your handling code here:
        user.setText("");
        pas.setText("");
        nama.setText("");
        al.setText("");
    }//GEN-LAST:event_canActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea al;
    private javax.swing.JButton can;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JButton home;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nama;
    private javax.swing.JPasswordField pas;
    private javax.swing.JButton save;
    private javax.swing.JTable t_admin;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
public void bersih(){
user.setText("");
pas.setText("");
nama.setText("");
al.setText("");
}

public void tampildata(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("username");
tabelnyo.addColumn("password");
tabelnyo.addColumn("nama");
tabelnyo.addColumn("alamat");

try{
koneksi();
String sql = "Select * from tb_admin order by username asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
});
}
t_admin.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}
