/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formFor.java
 *
 * Created on May 4, 2016, 7:23:30 PM
 */
package dispenda;
import java.text.*;
import koneksi.koneksi;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.lang.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableColumn;
import javax.swing.table.*;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author ZEUS
 */

public class formFor extends javax.swing.JFrame {
Connection c;
JasperReport JasRep;
JasperPrint JasPri;
Map<String, Object> param = new HashMap<String, Object>();
JasperDesign JasDes;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn;
    /** Creates new form formFor */
    public formFor() {
        initComponents();
        bersih();
        tampildata();
        lebarKolom();
        auto_number();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        kwp = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        no_form = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nm_bdn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        notelp_bdn = new javax.swing.JTextField();
        kod_bdn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nos_bdn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bu_bdn = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        almt_bdn = new javax.swing.JTextArea();
        s_bdn = new javax.swing.JTextField();
        tgl_bdn = new uz.ncipro.calendar.JDateTimePicker();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nm_ush = new javax.swing.JTextField();
        jbt = new javax.swing.JTextField();
        notelp_ush = new javax.swing.JTextField();
        kod_ush = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        almt_ush = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        npwpd = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        npwprd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_wp = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        sc = new javax.swing.JButton();
        prt = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        p1 = new javax.swing.JCheckBox();
        p2 = new javax.swing.JCheckBox();
        p3 = new javax.swing.JCheckBox();
        p5 = new javax.swing.JCheckBox();
        p4 = new javax.swing.JCheckBox();
        p6 = new javax.swing.JCheckBox();
        p9 = new javax.swing.JCheckBox();
        p7 = new javax.swing.JCheckBox();
        p8 = new javax.swing.JCheckBox();
        p10 = new javax.swing.JCheckBox();
        kwpajak = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 0));
        jLabel28.setText("FORMULIR PENDAFTARAN WAJIB PAJAK");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 0));
        jLabel29.setText("Nomor Formulir");

        no_form.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        no_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_formActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(0, 0, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Badan / Usaha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Nama Badan / Merk Usaha");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Alamat Usaha ");

        nm_bdn.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Nomor Telepon");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Kode Pos");

        notelp_bdn.setFont(new java.awt.Font("Arial", 0, 12));

        kod_bdn.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Surat Ijin Tempat Usaha");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Nomor Surat");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Tanggal");

        nos_bdn.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Bidang Usaha ");

        bu_bdn.setFont(new java.awt.Font("Arial", 0, 12));
        bu_bdn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biro Reklame", "Parkir", "Genset", "Hiburan", "Hotel / Rumah Kost", "Restoran" }));

        almt_bdn.setColumns(20);
        almt_bdn.setRows(5);
        jScrollPane3.setViewportView(almt_bdn);

        s_bdn.setFont(new java.awt.Font("Arial", 0, 12));

        tgl_bdn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10/8/16" }));
        tgl_bdn.setDisplayFormat("d/M/yy");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nos_bdn)
                                .addComponent(s_bdn)
                                .addComponent(kod_bdn)
                                .addComponent(notelp_bdn)
                                .addComponent(jScrollPane3)
                                .addComponent(nm_bdn, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tgl_bdn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bu_bdn, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nm_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(notelp_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kod_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(s_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nos_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(tgl_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bu_bdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Keterangan Pemilik / Pengelola Usaha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Nama Pemilik / Pengelola");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("Jabatan");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Alamat Tempat Tinggal");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel25.setForeground(new java.awt.Color(255, 255, 0));
        jLabel25.setText("Nomor Telepon");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText("Kode Pos");

        nm_ush.setFont(new java.awt.Font("Arial", 0, 12));

        jbt.setFont(new java.awt.Font("Arial", 0, 12));

        notelp_ush.setFont(new java.awt.Font("Arial", 0, 12));

        kod_ush.setFont(new java.awt.Font("Arial", 0, 12));

        almt_ush.setColumns(20);
        almt_ush.setRows(5);
        jScrollPane4.setViewportView(almt_ush);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kod_ush, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(notelp_ush, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jbt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(nm_ush, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(nm_ush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel19))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notelp_ush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kod_ush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("NPWPD yang diberikan");

        npwpd.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel27.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText("NPWRD yang diberikan");

        npwprd.setFont(new java.awt.Font("Arial", 0, 12));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        t_wp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        t_wp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_wpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_wp);

        cari.setFont(new java.awt.Font("Arial", 0, 12));

        sc.setBackground(new java.awt.Color(0, 0, 102));
        sc.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\s1.png")); // NOI18N
        sc.setBorderPainted(false);
        sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scActionPerformed(evt);
            }
        });

        prt.setBackground(new java.awt.Color(0, 0, 102));
        prt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/p1.png"))); // NOI18N
        prt.setBorderPainted(false);
        prt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prtActionPerformed(evt);
            }
        });

        jScrollPane5.setBorder(null);

        jPanel8.setBackground(new java.awt.Color(0, 0, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kewajiban Pajak / Retribusi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 11), new java.awt.Color(255, 255, 0))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(0, 0, 102));

        p1.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p1);
        p1.setFont(new java.awt.Font("Arial", 1, 11));
        p1.setForeground(new java.awt.Color(255, 255, 0));
        p1.setText("Pajak Hotel / Rumah Kost dan Restoran");
        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        p2.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p2);
        p2.setFont(new java.awt.Font("Arial", 1, 11));
        p2.setForeground(new java.awt.Color(255, 255, 0));
        p2.setText("Pajak Hiburan");
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p3.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p3);
        p3.setFont(new java.awt.Font("Arial", 1, 11));
        p3.setForeground(new java.awt.Color(255, 255, 0));
        p3.setText("Pajak Reklame");
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        p5.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p5);
        p5.setFont(new java.awt.Font("Arial", 1, 11));
        p5.setForeground(new java.awt.Color(255, 255, 0));
        p5.setText("Pajak Parkir");
        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        p4.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p4);
        p4.setFont(new java.awt.Font("Arial", 1, 11));
        p4.setForeground(new java.awt.Color(255, 255, 0));
        p4.setText("Pajak Penerangan Jalan");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        p6.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p6);
        p6.setFont(new java.awt.Font("Arial", 1, 11));
        p6.setForeground(new java.awt.Color(255, 255, 0));
        p6.setText("Pajak Genset");
        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });

        p9.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p9);
        p9.setFont(new java.awt.Font("Arial", 1, 11));
        p9.setForeground(new java.awt.Color(255, 255, 0));
        p9.setText("Retribusi Pasar ");
        p9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p9ActionPerformed(evt);
            }
        });

        p7.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p7);
        p7.setFont(new java.awt.Font("Arial", 1, 11));
        p7.setForeground(new java.awt.Color(255, 255, 0));
        p7.setText("Retribusi Kebersihan");
        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7ActionPerformed(evt);
            }
        });

        p8.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p8);
        p8.setFont(new java.awt.Font("Arial", 1, 11));
        p8.setForeground(new java.awt.Color(255, 255, 0));
        p8.setText("Retribusi Pasar Grosir dan Pertokoan");
        p8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8ActionPerformed(evt);
            }
        });

        p10.setBackground(new java.awt.Color(0, 0, 102));
        kwp.add(p10);
        p10.setFont(new java.awt.Font("Arial", 1, 11));
        p10.setForeground(new java.awt.Color(255, 255, 0));
        p10.setText("Retribusi Pemakaian Kekayaan Daerah");
        p10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1)
                            .addComponent(p2)
                            .addComponent(p3)
                            .addComponent(p4)
                            .addComponent(p5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p10)
                            .addComponent(p9)
                            .addComponent(p8)
                            .addComponent(p7)
                            .addComponent(p6)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(kwpajak, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addGap(275, 275, 275))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(kwpajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1)
                    .addComponent(p6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2)
                    .addComponent(p7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3)
                    .addComponent(p8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4)
                    .addComponent(p9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5)
                    .addComponent(p10))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel8);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\save.png")); // NOI18N
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.setBounds(20, 10, 50, 50);
        jDesktopPane1.add(save, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\edit.png")); // NOI18N
        edit.setBorderPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        edit.setBounds(90, 10, 50, 50);
        jDesktopPane1.add(edit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        delete.setBackground(new java.awt.Color(0, 0, 102));
        delete.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\del.png")); // NOI18N
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete.setBounds(160, 10, 60, 50);
        jDesktopPane1.add(delete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, 0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(npwprd)
                                        .addComponent(npwpd, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                    .addComponent(cari, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(npwpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(npwprd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cari)
                            .addComponent(sc, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        h1.setBackground(new java.awt.Color(0, 0, 102));
        h1.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\h1.png")); // NOI18N
        h1.setBorderPainted(false);
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 0));
        jLabel30.setText("REKLAME PERMANEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(no_form, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(682, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(349, 349, 349))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void openDataBase() //untuk koneksi dengan data base
{
try
    {
    Class.forName("com.mysql.jdbc.Driver"); c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
    System.out.println("Koneksi Berhasil");
    }   
        catch(ClassNotFoundException e)
        {
            System.out.println("Driver Tidak Ditemukan");
        }
    catch(Exception e)
    {
    System.out.println(e);
    }
}  
    private void auto_number() {
try{
    openDataBase();
//Class.forName("com.mysql.jdbc.Driver");
//Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
cn = conn.createStatement();
String SQL = "SELECT max(no_formulir) FROM tb_wp";
ResultSet rs= cn.executeQuery(SQL);
no_form.setText("F0001");
if(rs.next()){
String a=rs.getString(1);
String data[]=a.split("F");
int x=Integer.parseInt(data[1]);
x=x+1;
String hsl="";
if(x<10){
hsl=data[0].concat("F").concat("000").concat(Integer.toString(x));
}
else{
hsl=data[0].concat("F").concat("00").concat(Integer.toString(x));
}
no_form.setText(hsl);
}
}catch(Exception exc){
System.out.println(exc.getMessage());
}
} 
    
    private void p10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p10ActionPerformed
        // TODO add your handling code here:
        if (p10.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Retribusi Pemakaian Kekayaan Daerah");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p10ActionPerformed

    private void p8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8ActionPerformed
        // TODO add your handling code here:
        if (p8.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Retribusi Pasar Grosir dan Pertokoan");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p8ActionPerformed

    private void p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7ActionPerformed
        // TODO add your handling code here:
        if (p7.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Retribusi Kebersihan");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p7ActionPerformed

    private void p9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p9ActionPerformed
        // TODO add your handling code here:
        if (p9.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Retribusi Pasar");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p9ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        // TODO add your handling code here:
        if (p6.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Pajak Genset");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p6ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        // TODO add your handling code here:
        if (p4.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Pajak Penerangan Jalan");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p4ActionPerformed

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        // TODO add your handling code here:
        if (p5.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Pajak Parkir");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p5ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
        if (p3.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Pajak Reklame");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p3ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
        if (p2.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Pajak Hiburan");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p2ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
        if (p1.isSelected()){
            kwpajak.setEditable(true);
            kwpajak.setText("Pajak Hotel / Rumah Kost dan Restoran");
        }else{
            kwpajak.setEditable(false);
            kwpajak.setText("");
        }
}//GEN-LAST:event_p1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "delete from tb_wp where no_formulir='"+ no_form.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_wp set nama_badan='" + nm_bdn.getText() + "'," +
                    " alamat_badan='" + almt_bdn.getText() + "'," +
                    " notelp_badan='" + notelp_bdn.getText() + "'," +
                    " kodpos_badan='" + kod_bdn.getText() + "'," +
                    " surat_ijin_badan='" + s_bdn.getText() + "'," +
                    " nomor_surat='" + nos_bdn.getText() + "'," +
                    " tgl_badan='" + tgl_bdn.getSelectedItem() + "'," +
                    " bidang_usaha='" + bu_bdn.getSelectedItem() + "'," +
                    " nama_pemilik='" + nm_ush.getText() + "'," +
                    " jabatan='" + jbt.getText() + "'," +
                    " alamat_pemilik='" + almt_ush.getText() + "'," +
                    " notelp_pemilik='" + notelp_ush.getText() + "'," +
                    " kod_pemilik='" + kod_ush.getText() + "'," +
                    " kwpjk='" + kwpajak.getText() + "'," +
                    " Npwpd='" + npwpd.getText() + "'," +
                    " Npwprd='" + npwprd.getText() + "'" +
                    " where no_formulir='" + no_form.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());}
}//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            
            koneksi();
            String sql = "insert into tb_wp values ('"+ no_form.getText()+"','"+ nm_bdn.getText()+"','" + almt_bdn.getText() +"','" + notelp_bdn.getText()+"', '" + kod_bdn.getText() +"', '" + s_bdn.getText() +"','" + nos_bdn.getText() + "','" + tgl_bdn.getSelectedItem() + "','" + bu_bdn.getSelectedItem() + "','" + nm_ush.getText() + "','" + jbt.getText() + "','" + almt_ush.getText() + "','" + notelp_ush.getText() + "','" + kod_ush.getText() + "','" + kwpajak.getText() + "','" + npwpd.getText() + "','" + npwprd.getText() + "')";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_saveActionPerformed

    private void t_wpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_wpMouseClicked
        // TODO add your handling code here:
        int table = t_wp.getSelectedRow();
        //mengambil data dari table
        String a = t_wp.getValueAt(table, 0).toString();
        String b = t_wp.getValueAt(table, 1).toString();
        String t = t_wp.getValueAt(table, 2).toString();
        String d = t_wp.getValueAt(table, 3).toString();
        String e = t_wp.getValueAt(table, 4).toString();
        String f = t_wp.getValueAt(table, 5).toString();
        String g = t_wp.getValueAt(table, 6).toString();
        String h = t_wp.getValueAt(table, 7).toString();
        String i = t_wp.getValueAt(table, 8).toString();
        String j = t_wp.getValueAt(table, 9).toString();
        String k = t_wp.getValueAt(table, 10).toString();
        String l = t_wp.getValueAt(table, 11).toString();
        String m = t_wp.getValueAt(table, 12).toString();
        String n = t_wp.getValueAt(table, 13).toString();
        String o = t_wp.getValueAt(table, 14).toString();
        String p = t_wp.getValueAt(table, 15).toString();
        String q = t_wp.getValueAt(table, 16).toString();
        
        
        no_form.setText(a);
        nm_bdn.setText(b);
        almt_bdn.setText(t);
        notelp_bdn.setText(d);
        kod_bdn.setText(e);
        s_bdn.setText(f);
        nos_bdn.setText(g);
        tgl_bdn.setSelectedItem(h);
        bu_bdn.setSelectedItem(i);
        nm_ush.setText(j);
        jbt.setText(k);
        almt_ush.setText(l);
        notelp_ush.setText(m);
        kod_bdn.setText(n);
        kwpajak.setText(o);
        npwpd.setText(p);
        npwprd.setText(q);
}//GEN-LAST:event_t_wpMouseClicked

    private void no_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_formActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_no_formActionPerformed

    private void scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scActionPerformed

DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("no_formulir");
tabelnyo.addColumn("nama_badan");
tabelnyo.addColumn("alamat_badan");
tabelnyo.addColumn("notelp_badan");
tabelnyo.addColumn("kodpos_badan");
tabelnyo.addColumn("surat_ijin_badan");
tabelnyo.addColumn("nomor_surat");
tabelnyo.addColumn("tgl_badan");
tabelnyo.addColumn("bidang_usaha");
tabelnyo.addColumn("nama_pemilik");
tabelnyo.addColumn("jabatan");
tabelnyo.addColumn("alamat_pemilik");
tabelnyo.addColumn("notelp_pemilik");
tabelnyo.addColumn("kod_pemilik");
tabelnyo.addColumn("kwpjk");
tabelnyo.addColumn("Npwpd");
tabelnyo.addColumn("Npwprd");

try {
    koneksi();
    String sql = "select * from tb_wp where no_formulir like '%"+cari.getText()+"%'";
    ResultSet rs = cn.executeQuery(sql);
    while (rs.next())
    {
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
rs.getString(16),
rs.getString(17),
});
}
            t_wp.setModel(tabelnyo);
        } catch (Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_scActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
dispose();
    }//GEN-LAST:event_h1ActionPerformed

    private void prtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prtActionPerformed
        // TODO add your handling code here:
       try {
            // parameter
            String parameterNama = cari.getText();
                
            //set parameters
            //Map param = new HashMap();
            param.put("no_formulir", parameterNama);
                
            File file = new File("src/Report/formulir.jrxml");
            JasDes = JRXmlLoader.load(file);
            //param.clear();%
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param, conn);
            JasperViewer.viewReport(JasPri, false); 
            
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_prtActionPerformed

    public void lebarKolom(){ 
        TableColumn column;
        t_wp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = t_wp.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = t_wp.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = t_wp.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = t_wp.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = t_wp.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = t_wp.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = t_wp.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = t_wp.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = t_wp.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = t_wp.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = t_wp.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = t_wp.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = t_wp.getColumnModel().getColumn(12); 
        column.setPreferredWidth(250);
        column = t_wp.getColumnModel().getColumn(13); 
        column.setPreferredWidth(250);
        column = t_wp.getColumnModel().getColumn(14); 
        column.setPreferredWidth(250);
         column = t_wp.getColumnModel().getColumn(15); 
        column.setPreferredWidth(250);
         column = t_wp.getColumnModel().getColumn(16); 
        column.setPreferredWidth(250);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new formFor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt_bdn;
    private javax.swing.JTextArea almt_ush;
    private javax.swing.JComboBox bu_bdn;
    private javax.swing.JTextField cari;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton h1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jbt;
    private javax.swing.JTextField kod_bdn;
    private javax.swing.JTextField kod_ush;
    private javax.swing.ButtonGroup kwp;
    private javax.swing.JTextField kwpajak;
    private javax.swing.JTextField nm_bdn;
    private javax.swing.JTextField nm_ush;
    private javax.swing.JTextField no_form;
    private javax.swing.JTextField nos_bdn;
    private javax.swing.JTextField notelp_bdn;
    private javax.swing.JTextField notelp_ush;
    private javax.swing.JTextField npwpd;
    private javax.swing.JTextField npwprd;
    private javax.swing.JCheckBox p1;
    private javax.swing.JCheckBox p10;
    private javax.swing.JCheckBox p2;
    private javax.swing.JCheckBox p3;
    private javax.swing.JCheckBox p4;
    private javax.swing.JCheckBox p5;
    private javax.swing.JCheckBox p6;
    private javax.swing.JCheckBox p7;
    private javax.swing.JCheckBox p8;
    private javax.swing.JCheckBox p9;
    private javax.swing.JButton prt;
    private javax.swing.JTextField s_bdn;
    private javax.swing.JButton save;
    private javax.swing.JButton sc;
    private javax.swing.JTable t_wp;
    private uz.ncipro.calendar.JDateTimePicker tgl_bdn;
    // End of variables declaration//GEN-END:variables

public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
public void bersih(){

no_form.setText("");
nm_bdn.setText("");
almt_bdn.setText("");
notelp_bdn.setText("");
kod_bdn.setText("");
s_bdn.setText("");
nos_bdn.setText("");
tgl_bdn.setSelectedItem ("");
bu_bdn.setSelectedItem ("");
nm_ush.setText ("");
jbt.setText ("");
almt_ush.setText ("");
notelp_ush.setText ("");
kod_bdn.setText ("");
kwpajak.setText ("");
npwpd.setText ("");
npwprd.setText ("");
}
public void tampildata(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("no_formulir");
tabelnyo.addColumn("nama_badan");
tabelnyo.addColumn("alamat_badan");
tabelnyo.addColumn("notelp_badan");
tabelnyo.addColumn("kodpos_badan");
tabelnyo.addColumn("surat_ijin_badan");
tabelnyo.addColumn("nomor_surat");
tabelnyo.addColumn("tgl_badan");
tabelnyo.addColumn("bidang_usaha");
tabelnyo.addColumn("nama_pemilik");
tabelnyo.addColumn("jabatan");
tabelnyo.addColumn("alamat_pemilik");
tabelnyo.addColumn("notelp_pemilik");
tabelnyo.addColumn("kod_pemilik");
tabelnyo.addColumn("kwpjk");
tabelnyo.addColumn("Npwpd");
tabelnyo.addColumn("Npwprd");

try{
koneksi();
String sql = "Select * from tb_wp order by no_formulir asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
rs.getString(16),
rs.getString(17),

});
}
t_wp.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}