/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * insidentil.java
 *
 * Created on Jul 30, 2016, 4:12:33 PM
 */

package dispenda;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
import java.text.DecimalFormat;
import javax.swing.JFormattedTextField;
/**
 *
 * @author Agung
 */
public class insidentil extends javax.swing.JFrame {
Connection c;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn; 
    /** Creates new form insidentil */
    public insidentil() {
        initComponents();
        bersih();
        tampildata();
        auto_number();
        tampilnpwp();
        lebarKolom();
        j1.setVisible(false);
        j2.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nspt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        mp = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        j1 = new javax.swing.JDesktopPane();
        k1 = new javax.swing.JCheckBox();
        k2 = new javax.swing.JCheckBox();
        j2 = new javax.swing.JPanel();
        m5 = new javax.swing.JCheckBox();
        m6 = new javax.swing.JCheckBox();
        m7 = new javax.swing.JCheckBox();
        m8 = new javax.swing.JCheckBox();
        j3 = new javax.swing.JDesktopPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        mu = new uz.ncipro.calendar.JDateTimePicker();
        sel = new uz.ncipro.calendar.JDateTimePicker();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        r1 = new javax.swing.JCheckBox();
        r2 = new javax.swing.JCheckBox();
        r3 = new javax.swing.JCheckBox();
        r4 = new javax.swing.JCheckBox();
        r5 = new javax.swing.JCheckBox();
        r6 = new javax.swing.JCheckBox();
        r7 = new javax.swing.JCheckBox();
        r8 = new javax.swing.JCheckBox();
        jr = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jmp = new javax.swing.JTextField();
        lks = new javax.swing.JComboBox();
        tbr = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jdl = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane8 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_spt = new javax.swing.JTable();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        del = new javax.swing.JButton();
        edt = new javax.swing.JButton();
        sv = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel15 = new javax.swing.JLabel();
        npwpd2 = new javax.swing.JComboBox();
        hm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jDesktopPane2.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel25.setForeground(new java.awt.Color(255, 255, 0));
        jLabel25.setText("SURAT PEMBERITAHUAN PAJAK DAERAH");
        jLabel25.setBounds(50, 10, 494, 29);
        jDesktopPane2.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("PAJAK REKLAME INSIDENTIL");
        jLabel13.setBounds(130, 50, 350, 29);
        jDesktopPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBounds(30, 110, 590, 90);
        jDesktopPane1.add(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nspt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nsptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("No SPTPD");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Masa Pajak");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Tahun Pajak");

        mp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel14))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(tp)
                        .add(nspt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                    .add(mp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nspt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(17, 17, 17)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(mp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(tp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBounds(630, 110, 310, 135);
        jDesktopPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jDesktopPane5.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        j1.setBackground(new java.awt.Color(0, 0, 102));
        j1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reklame Kain", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        k1.setBackground(new java.awt.Color(0, 0, 102));
        k1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        k1.setForeground(new java.awt.Color(255, 255, 0));
        k1.setText("Baliho / Tenda");
        k1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k1ActionPerformed(evt);
            }
        });
        k1.setBounds(30, 30, 190, 23);
        j1.add(k1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        k2.setBackground(new java.awt.Color(0, 0, 102));
        k2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        k2.setForeground(new java.awt.Color(255, 255, 0));
        k2.setText("Spanduk / Banner / Umbul-Umbul");
        k2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k2ActionPerformed(evt);
            }
        });
        k2.setBounds(30, 80, 230, 23);
        j1.add(k2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j1.setBounds(20, 20, 350, 130);
        jDesktopPane5.add(j1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j2.setBackground(new java.awt.Color(0, 0, 102));
        j2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reklame Melekat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), new java.awt.Color(255, 255, 0))); // NOI18N

        m5.setBackground(new java.awt.Color(0, 0, 102));
        m5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        m5.setForeground(new java.awt.Color(255, 255, 0));
        m5.setText("Ukuran Kwarto");
        m5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m5ActionPerformed(evt);
            }
        });

        m6.setBackground(new java.awt.Color(0, 0, 102));
        m6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        m6.setForeground(new java.awt.Color(255, 255, 0));
        m6.setText("Ukuran Folio");
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });

        m7.setBackground(new java.awt.Color(0, 0, 102));
        m7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        m7.setForeground(new java.awt.Color(255, 255, 0));
        m7.setText("Ukuran Double Foto");
        m7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m7ActionPerformed(evt);
            }
        });

        m8.setBackground(new java.awt.Color(0, 0, 102));
        m8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        m8.setForeground(new java.awt.Color(255, 255, 0));
        m8.setText("Ukuran Lebih Dari Ukuran Diatas");
        m8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m8ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout j2Layout = new org.jdesktop.layout.GroupLayout(j2);
        j2.setLayout(j2Layout);
        j2Layout.setHorizontalGroup(
            j2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(j2Layout.createSequentialGroup()
                .add(45, 45, 45)
                .add(j2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(m8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(j2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(m7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 212, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(m5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .add(m6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        j2Layout.setVerticalGroup(
            j2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(j2Layout.createSequentialGroup()
                .addContainerGap()
                .add(m5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(m6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(m7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(m8)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        j2.setBounds(19, 20, 350, 130);
        jDesktopPane5.add(j2, javax.swing.JLayeredPane.DRAG_LAYER);
        j2.getAccessibleContext().setAccessibleParent(jPanel1);

        j3.setBackground(new java.awt.Color(0, 0, 102));
        j3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText("Selesai");
        jLabel18.setBounds(10, 60, 80, 20);
        j3.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("Jangka Waktu Pemasangan");
        jLabel20.setBounds(10, 10, 160, 14);
        j3.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Mulai");
        jLabel21.setBounds(10, 34, 80, 20);
        j3.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mu.setDisplayFormat("d/M/yy ");
        mu.setBounds(130, 30, 190, 20);
        j3.add(mu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sel.setDisplayFormat("d/M/yy ");
        sel.setBounds(130, 60, 190, 20);
        j3.add(sel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j3.setBounds(20, 170, 350, 100);
        jDesktopPane5.add(j3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane7.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jDesktopPane4.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        r1.setBackground(new java.awt.Color(0, 0, 102));
        r1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r1.setForeground(new java.awt.Color(255, 255, 0));
        r1.setText("Reklame Kain");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        r1.setBounds(30, 40, 170, 23);
        jDesktopPane4.add(r1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r2.setBackground(new java.awt.Color(0, 0, 102));
        r2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r2.setForeground(new java.awt.Color(255, 255, 0));
        r2.setText("Reklame Papan / Tinplate");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        r2.setBounds(30, 60, 170, 23);
        jDesktopPane4.add(r2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r3.setBackground(new java.awt.Color(0, 0, 102));
        r3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r3.setForeground(new java.awt.Color(255, 255, 0));
        r3.setText("Reklame Film / Slide");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        r3.setBounds(30, 80, 170, 23);
        jDesktopPane4.add(r3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r4.setBackground(new java.awt.Color(0, 0, 102));
        r4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r4.setForeground(new java.awt.Color(255, 255, 0));
        r4.setText("Reklame Udara / Balon");
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        r4.setBounds(30, 100, 170, 23);
        jDesktopPane4.add(r4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r5.setBackground(new java.awt.Color(0, 0, 102));
        r5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r5.setForeground(new java.awt.Color(255, 255, 0));
        r5.setText("Reklame Berjalan / Kendaraan");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });
        r5.setBounds(210, 40, 200, 23);
        jDesktopPane4.add(r5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r6.setBackground(new java.awt.Color(0, 0, 102));
        r6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r6.setForeground(new java.awt.Color(255, 255, 0));
        r6.setText("Reklame Suara");
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        r6.setBounds(210, 60, 200, 23);
        jDesktopPane4.add(r6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r7.setBackground(new java.awt.Color(0, 0, 102));
        r7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r7.setForeground(new java.awt.Color(255, 255, 0));
        r7.setText("Reklame Peragaan");
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });
        r7.setBounds(210, 80, 200, 23);
        jDesktopPane4.add(r7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        r8.setBackground(new java.awt.Color(0, 0, 102));
        r8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        r8.setForeground(new java.awt.Color(255, 255, 0));
        r8.setText("Reklame Melekat / Sticker");
        r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8ActionPerformed(evt);
            }
        });
        r8.setBounds(210, 100, 200, 23);
        jDesktopPane4.add(r8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrActionPerformed(evt);
            }
        });
        jr.setBounds(120, 10, 250, 20);
        jDesktopPane4.add(jr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText(" Jenis Reklame");
        jLabel17.setBounds(20, 10, 90, 14);
        jDesktopPane4.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBounds(20, 20, 420, 136);
        jDesktopPane7.add(jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Tarif Bahan Reklame");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText("Lokasi Pemasangan");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText("Jumlah Pemasangan");

        lks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jalan Urip Sumoharjo", "Jalan A. Yani", "Jalan Pahlawan", "Jalan Yos Sudarso", "Jalan Basuki Rahmat", "Jalan S. Parman", "Jalan Thamrin", "Jalan MT Haryono", "Jalan Panjaitan", "Jalan Soekarno Hatta", "Jalan Trunojoyo", "Jalan MJ Sungkono", "Jalan Mastrip", "Jalan Ring Road", "Jalan Cokroaminoto", "Jalan Musi", "Jalan HA Salim", "Jalan Kolonel Mahardi", "Jalan P. Sudirman ", "Jalan Setia Budi", "Jalan Aloon-Aloon Barat", "Jalan Aloon-Aloon Timur", "Jalan Bogowonto", "Jalan Kutai", "Jalan Dr. Soetomo", "Jalan Diponegoro", "Jalan Dr. Cipto", "Jalan Kenari", "Jalan Kemiri", "Jalan Ciliwung", "Jalan Salak", "Jalan Kapuas", "Jalan Sulawesi", "Jalan Kalimantan", "Jalan P kemerdekaan", "Jalan Jawa", "Jalan Sumatera", "Jalan Kompol Sunaryo", "Jalan Sumber Karya", "Jalan Kelapa Manis", "Jalan Slamet Riyadi", "Jalan Cokrobasonto", "Jalan Tanjung Raya", "Jalan Imam Bonjol", "Jalan Bali", "Jalan Barito" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setText("Judul Reklame");

        jdl.setColumns(20);
        jdl.setRows(5);
        jScrollPane3.setViewportView(jdl);

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel24, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel22)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel16, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel23, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(40, 40, 40)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane3)
                    .add(jmp)
                    .add(tbr)
                    .add(lks, 0, 220, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(tbr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(lks, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(jmp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel24)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        jScrollPane1.setBounds(20, 170, 420, 100);
        jDesktopPane7.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jDesktopPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 461, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 26, Short.MAX_VALUE)
                .add(jDesktopPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 386, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jDesktopPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 288, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jDesktopPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Form SPTPD", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jDesktopPane8.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_spt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_spt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_spt);

        jScrollPane2.setBounds(40, 100, 810, 140);
        jDesktopPane8.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane9.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        del.setBackground(new java.awt.Color(0, 0, 102));
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/del.png"))); // NOI18N
        del.setBorderPainted(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        del.setBounds(220, 10, 60, 60);
        jDesktopPane9.add(del, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edt.setBackground(new java.awt.Color(0, 0, 102));
        edt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/edit.png"))); // NOI18N
        edt.setBorderPainted(false);
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });
        edt.setBounds(130, 10, 60, 60);
        jDesktopPane9.add(edt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sv.setBackground(new java.awt.Color(0, 0, 102));
        sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/save.png"))); // NOI18N
        sv.setBorderPainted(false);
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });
        sv.setBounds(30, 10, 70, 60);
        jDesktopPane9.add(sv, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane9.setBounds(30, 10, 310, 80);
        jDesktopPane8.add(jDesktopPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Data SPTPD Reklame Insidental");
        jLabel12.setBounds(280, 260, 370, 29);
        jDesktopPane8.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data Reklame", jPanel2);

        jTabbedPane1.setBounds(30, 260, 910, 350);
        jDesktopPane1.add(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("NPWPD ");
        jLabel15.setFocusable(false);
        jLabel15.setVerifyInputWhenFocusTarget(false);
        jLabel15.setBounds(20, 10, 47, 15);
        jDesktopPane3.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        npwpd2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "===== Pilih N P W P D =====" }));
        npwpd2.setBounds(83, 10, 190, 20);
        jDesktopPane3.add(npwpd2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(30, 210, 290, 40);
        jDesktopPane1.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hm.setBackground(new java.awt.Color(0, 0, 102));
        hm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/h1.png"))); // NOI18N
        hm.setBorderPainted(false);
        hm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmActionPerformed(evt);
            }
        });
        hm.setBounds(440, 620, 90, 30);
        jDesktopPane1.add(hm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 962, 100);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jDesktopPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 671, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void openDataBase() //untuk koneksi dengan data base
{
try
    {
    Class.forName("com.mysql.jdbc.Driver"); c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
    System.out.println("Koneksi Berhasil");
    }   
        catch(ClassNotFoundException e)
        {
            System.out.println("Driver Tidak Ditemukan");
        }
    catch(Exception e)
    {
    System.out.println(e);
    }
}

private void auto_number() {
try{
 openDataBase();
//Class.forName("com.mysql.jdbc.Driver");
//Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
cn = conn.createStatement();
String SQL = "SELECT max(nosptpd) FROM tb_sptinsidental";
ResultSet rs= cn.executeQuery(SQL);
nspt.setText("SPTI001");
if(rs.next()){
String a=rs.getString(1);
String data[]=a.split("SPTI");
int x=Integer.parseInt(data[1]);
x=x+1;
String hsl="";
if(x<10){
hsl=data[0].concat("SPTI").concat("00").concat(Integer.toString(x));
}
else{
hsl=data[0].concat("SPTI").concat("0").concat(Integer.toString(x));
}
nspt.setText(hsl);
}
}catch(Exception exc){
System.out.println(exc.getMessage());
}
} 

public void tampilnpwp(){
        try {
            
            Statement statement = (Statement) c.createStatement();  
            String sql = "SELECT * FROM tb_wpinsidental";
            ResultSet resultSet = statement.executeQuery(sql);
            
            while(resultSet.next()){
                npwpd2.addItem(resultSet.getString("npwpd"));
            }
            resultSet.close();
            statement.close();
            
            System.out.println("Tampil Data Berhasil");
        } catch (SQLException ex) {
            System.out.println("Tampil Data Gagal \n Pesan :" + ex.toString());
        }
}
    private void nsptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nsptActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nsptActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        // TODO add your handling code here:
        if (r6.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Suara");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (r6.isSelected()){
            tbr.setEditable(true);
            tbr.setText("100000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_r6ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        // TODO add your handling code here:
        if (r7.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Peragaan");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (r7.isSelected()){
            tbr.setEditable(true);
            tbr.setText("100000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_r7ActionPerformed

    private void jrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
        if(r1.isSelected()==true){
            j1.setVisible(true);
        }else if(r1.isSelected()==false){
            j1.setVisible(false);
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void k1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k1ActionPerformed
        // TODO add your handling code here:
        if (k1.isSelected()){
            jr.setEditable(true);
            jr.setText("Baliho / Tenda");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (k1.isSelected()){
            tbr.setEditable(true);
            tbr.setText("160000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_k1ActionPerformed

    private void r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8ActionPerformed
        // TODO add your handling code here:
         if(r8.isSelected()==true){
            j2.setVisible(true);
        }else if(r8.isSelected()==false){
            j2.setVisible(false);
        }
         if (r8.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Melekat");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
    }//GEN-LAST:event_r8ActionPerformed

    private void k2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k2ActionPerformed
        // TODO add your handling code here:
        if (k2.isSelected()){
            jr.setEditable(true);
            jr.setText("Spanduk / Banner / Umbul-Umbul");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (k2.isSelected()){
            tbr.setEditable(true);
            tbr.setText("40000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_k2ActionPerformed

    private void hmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_hmActionPerformed

    private void m5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m5ActionPerformed
        // TODO add your handling code here:
        if (m5.isSelected()){
            tbr.setEditable(true);
            tbr.setText("10000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_m5ActionPerformed

    private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
        // TODO add your handling code here:
        if (m6.isSelected()){
            tbr.setEditable(true);
            tbr.setText("10000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_m6ActionPerformed

    private void m7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m7ActionPerformed
        // TODO add your handling code here:
        if (m7.isSelected()){
            tbr.setEditable(true);
            tbr.setText("20000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_m7ActionPerformed

    private void m8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m8ActionPerformed
        // TODO add your handling code here:
        if (m8.isSelected()){
            tbr.setEditable(true);
            tbr.setText("30000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_m8ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
          if (r2.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Papan / Tinplate");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (r2.isSelected()){
            tbr.setEditable(true);
            tbr.setText("40000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
         if (r3.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Film / Slide");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (r3.isSelected()){
            tbr.setEditable(true);
            tbr.setText("400000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        // TODO add your handling code here:
         if (r5.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Berjalan / Kendaraan");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (r5.isSelected()){
            tbr.setEditable(true);
            tbr.setText("100000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_r5ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        // TODO add your handling code here:
        if (r4.isSelected()){
            jr.setEditable(true);
            jr.setText("Reklame Udara / Balon");
        }else{
            jr.setEditable(false);
            jr.setText("");
        }
        if (r4.isSelected()){
            tbr.setEditable(true);
            tbr.setText("400000");
        }else{
            tbr.setEditable(false);
            tbr.setText("");
        }
    }//GEN-LAST:event_r4ActionPerformed

    private void tb_sptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sptMouseClicked
        // TODO add your handling code here:
         int table = tb_spt.getSelectedRow();
//mengambil data dari table
String a = tb_spt.getValueAt(table, 0).toString();
String b = tb_spt.getValueAt(table, 1).toString();
String c = tb_spt.getValueAt(table, 2).toString();
String d = tb_spt.getValueAt(table, 3).toString();
String e = tb_spt.getValueAt(table, 4).toString();
String f = tb_spt.getValueAt(table, 5).toString();
String g = tb_spt.getValueAt(table, 6).toString();
String h = tb_spt.getValueAt(table, 7).toString();
String i = tb_spt.getValueAt(table, 8).toString();
String j = tb_spt.getValueAt(table, 9).toString();
String k = tb_spt.getValueAt(table, 10).toString();


nspt.setText(a);
mp.setSelectedItem(b);
tp.setText(c);
npwpd2.setSelectedItem(d);
jr.setText(e);
tbr.setText(f);
lks.setSelectedItem (g);
jmp.setText (h);
jdl.setText (i);
mu.setSelectedItem (j);
sel.setSelectedItem (k);            
    }//GEN-LAST:event_tb_sptMouseClicked
public void lebarKolom(){ 
        TableColumn column;
        tb_spt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_spt.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_spt.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_spt.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tb_spt.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_spt.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_spt.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_spt.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = tb_spt.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tb_spt.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tb_spt.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tb_spt.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
    }
    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_sptpd set masa='" + mp.getSelectedItem() + "'," +
                    " tahun='" + tp.getText() + "'," +
                    " npwp_2='" + npwpd2.getSelectedItem() + "'," +
                    " jenis='" + jr.getText() + "'," +
                    " tarif='" + tbr.getText() + "'," +
                    " lokasi='" + lks.getSelectedItem() + "'," +
                    " jumlah='" + jmp.getText() + "'," +
                    " judul='" + jdl.getText() + "'," +
                    " mulai='" + mu.getSelectedItem() + "'," +
                    " selesai='" + sel.getSelectedItem() + "'" +
                    " where nosptpd='" + nspt.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());}
    }//GEN-LAST:event_edtActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "delete from tb_sptinsidental where nosptpd='"+ nspt.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_delActionPerformed

    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        try{
            
            koneksi();
            String sql = "insert into tb_sptinsidental values ('"+ nspt.getText()+"',"
                    + "'" + mp.getSelectedItem()+"',"
                    + "'" + tp.getText() +"',"
                    + "'" + npwpd2.getSelectedItem()+"', "
                    + "'" + jr.getText() +"',"
                    + "'" + tbr.getText() +"',"
                    + "'" + lks.getSelectedItem() +"',"
                    + "'" + jmp.getText() + "',"
                    + "'" + jdl.getText() + "',"
                    + "'" + mu.getSelectedItem() + "',"
                    + "'" + sel.getSelectedItem() +"')";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_svActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insidentil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton del;
    private javax.swing.JButton edt;
    private javax.swing.JButton hm;
    private javax.swing.JDesktopPane j1;
    private javax.swing.JPanel j2;
    private javax.swing.JDesktopPane j3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jdl;
    private javax.swing.JTextField jmp;
    private javax.swing.JTextField jr;
    private javax.swing.JCheckBox k1;
    private javax.swing.JCheckBox k2;
    private javax.swing.JComboBox lks;
    private javax.swing.JCheckBox m5;
    private javax.swing.JCheckBox m6;
    private javax.swing.JCheckBox m7;
    private javax.swing.JCheckBox m8;
    private javax.swing.JComboBox mp;
    private uz.ncipro.calendar.JDateTimePicker mu;
    private javax.swing.JComboBox npwpd2;
    private javax.swing.JTextField nspt;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r2;
    private javax.swing.JCheckBox r3;
    private javax.swing.JCheckBox r4;
    private javax.swing.JCheckBox r5;
    private javax.swing.JCheckBox r6;
    private javax.swing.JCheckBox r7;
    private javax.swing.JCheckBox r8;
    private uz.ncipro.calendar.JDateTimePicker sel;
    private javax.swing.JButton sv;
    private javax.swing.JTable tb_spt;
    private javax.swing.JTextField tbr;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}

public void bersih(){
nspt.setText("");
mp.setSelectedItem("");
tp.setText("");
npwpd2.setSelectedItem("");
jr.setText("");
tbr.setText ("");
lks.setSelectedItem ("");
jmp.setText ("");
jdl.setText ("");
mu.setSelectedItem ("");
sel.setSelectedItem ("");
}

public void tampildata(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nosptpd");
tabelnyo.addColumn("masa");
tabelnyo.addColumn("tahun");
tabelnyo.addColumn("npwp_2");
tabelnyo.addColumn("jenis");
tabelnyo.addColumn("tarif");
tabelnyo.addColumn("jalan");
tabelnyo.addColumn("jumlah");
tabelnyo.addColumn("judul");
tabelnyo.addColumn("mulai");
tabelnyo.addColumn("selesai");

try{
koneksi();
String sql = "Select * from tb_sptinsidental order by nosptpd asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
});
}
tb_spt.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}
