/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * kdatainsidental.java
 *
 * Created on Aug 10, 2016, 8:32:57 PM
 */
package dispenda;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
/**
 *
 * @author Agung
 */
public class kdatainsidental extends javax.swing.JFrame {
Connection c;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn;
    /** Creates new form kdatainsidental */
    public kdatainsidental() {
        initComponents();
        bersih();
        tampildata();
        auto_number();
        lebarKolom();
        tampilnpwpd();
        tampilnpwpd1();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        almbdn = new javax.swing.JTextArea();
        nmbdn = new javax.swing.JTextField();
        nmpml = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        almpml = new javax.swing.JTextArea();
        nofor = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kdatains = new javax.swing.JTable();
        thn = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jrek = new javax.swing.JTextField();
        lok = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jml = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jdrek = new javax.swing.JTextArea();
        mul = new uz.ncipro.calendar.JDateTimePicker();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sls = new uz.ncipro.calendar.JDateTimePicker();
        npwpd = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        tbr1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nokd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        h3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Nama Badan");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Alamat Badan");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Nama Pemilik");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Alamat Pemilik");

        almbdn.setColumns(20);
        almbdn.setRows(5);
        jScrollPane4.setViewportView(almbdn);

        almpml.setColumns(20);
        almpml.setRows(5);
        jScrollPane5.setViewportView(almpml);

        nofor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "===== No Formulir =====" }));
        nofor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noforItemStateChanged(evt);
            }
        });
        nofor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noforActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("No Formulir");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nofor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nmpml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(nmbdn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmbdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(nofor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmpml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("KARTU DATA PAJAK REKLAME INSIDENTIL");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Tahun Pajak");

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\save.png")); // NOI18N
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\edit.png")); // NOI18N
        edit.setBorderPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        del.setBackground(new java.awt.Color(0, 0, 102));
        del.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\del.png")); // NOI18N
        del.setBorderPainted(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_kdatains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_kdatains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_kdatainsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_kdatains);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Jenis Reklame");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Lokasi Pemasangan");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Judul Reklame");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Jumlah Pemasangan");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("Jangka Waktu Pemasangan");

        jdrek.setColumns(20);
        jdrek.setRows(5);
        jScrollPane6.setViewportView(jdrek);

        mul.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10/8/16" }));
        mul.setDisplayFormat("d/M/yy");
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Mulai");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Selesai");

        sls.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10/8/16" }));
        sls.setDisplayFormat("d/M/yy");

        npwpd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "===== Pilih N P W P D =====" }));
        npwpd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                npwpdItemStateChanged(evt);
            }
        });
        npwpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npwpdActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("NPWPD");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Tarif Bahan Reklame");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(lok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(tbr1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jrek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(sls, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addComponent(npwpd, javax.swing.GroupLayout.Alignment.LEADING, 0, 217, Short.MAX_VALUE))
                        .addGap(124, 124, 124))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel19)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel21)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(npwpd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jml, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel3);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("No Kartu");

        h3.setBackground(new java.awt.Color(0, 0, 102));
        h3.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\h1.png")); // NOI18N
        h3.setBorderPainted(false);
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(nokd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nokd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void openDataBase() //untuk koneksi dengan data base
{
try
    {
    Class.forName("com.mysql.jdbc.Driver"); c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
    System.out.println("Koneksi Berhasil");
    }   
        catch(ClassNotFoundException e)
        {
            System.out.println("Driver Tidak Ditemukan");
        }
    catch(Exception e)
    {
    System.out.println(e);
    }
}   
    
    public void tampilnpwpd(){
        try {
            
            Statement statement = (Statement) c.createStatement();  
            String sql = "SELECT * FROM tb_wpinsidental";
            ResultSet resultSet = statement.executeQuery(sql);
            
            while(resultSet.next()){
                nofor.addItem(resultSet.getString("noform"));
            }
            
            resultSet.close();
            statement.close();
            
            System.out.println("Tampil Data Berhasil");
        }   catch (SQLException ex) {
            System.out.println("Tampil Data Gagal \n Pesan :" + ex.toString());
        }
}

public void tampilnpwpd1(){
        try {
            
            Statement statement = (Statement) c.createStatement();  
            String sql = "SELECT * FROM tb_sptinsidental";
            ResultSet resultSet = statement.executeQuery(sql);
            
            while(resultSet.next()){
                npwpd.addItem(resultSet.getString("npwp_2"));
            }
            
            resultSet.close();
            statement.close();
            
            System.out.println("Tampil Data Berhasil");
        }   catch (SQLException ex) {
            System.out.println("Tampil Data Gagal \n Pesan :" + ex.toString());
        }
}

private void auto_number() {
 try{
        openDataBase();
//Class.forName("com.mysql.jdbc.Driver");
//Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
cn = conn.createStatement();
String SQL = "SELECT max(nokartu) FROM tb_kdinsidental";


ResultSet rs= cn.executeQuery(SQL);
nokd.setText("KI0001");
if(rs.next()){
String a=rs.getString(1);
String data[]=a.split("KI");
int x=Integer.parseInt(data[1]);
x=x+1;
String hsl="";
if(x<10){
hsl=data[0].concat("KI").concat("000").concat(Integer.toString(x));
}
else{
hsl=data[0].concat("KI").concat("00").concat(Integer.toString(x));
}
nokd.setText(hsl);
}
}catch(Exception exc){
System.out.println(exc.getMessage());
}
} 

public void lebarKolom(){ 
        TableColumn column;
        tb_kdatains.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_kdatains.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_kdatains.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_kdatains.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tb_kdatains.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_kdatains.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_kdatains.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_kdatains.getColumnModel().getColumn(6); 
        column.setPreferredWidth(250);
        column = tb_kdatains.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tb_kdatains.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tb_kdatains.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tb_kdatains.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = tb_kdatains.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = tb_kdatains.getColumnModel().getColumn(12); 
        column.setPreferredWidth(225);
}
    private void noforItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noforItemStateChanged
        // TODO add your handling code here:
        try{
            Statement stm=c.createStatement();
            r=stm.executeQuery("select * from tb_wpinsidental where noform='"+nofor.getSelectedItem()+"'");
            while(r.next()){
                nmbdn.setText(r.getString("nmbd"));
                almbdn.setText(r.getString("almbd"));
                nmpml.setText(r.getString("nmpm"));
                almpml.setText(r.getString("almpm"));
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_noforItemStateChanged

    private void noforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noforActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_noforActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            
            koneksi();
            String sql = "insert into tb_kdinsidental values ('"+ nokd.getText()+"',"
                    + "'"+ nmbdn.getText()+"',"
                    + "'" + almbdn.getText() +"',"
                    + "'" + nmpml.getText()+"', "
                    + "'" + almpml.getText() +"', "
                    + "'"+ npwpd.getSelectedItem()+"',"
                    + "'" + jrek.getText() +"',"
                    + "'" + lok.getText() + "',"
                    + "'" + jdrek.getText() + "',"
                    + "'" + tbr1.getText() + "',"
                    + "'" + jml.getText() + "',"
                    + "'" + mul.getSelectedItem() + "',"
                    + "'" + sls.getSelectedItem() + "')";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_kdinsidental set npw='" + npwpd.getSelectedItem() + "'," +
                    " namabad='" + nmbdn.getText() + "'," +
                    " almbad='" + almbdn.getText() + "'," +
                    " namapem='" + nmpml.getText() + "'," +
                    " almpem='" + almpml.getText() + "'," +
                    " jenrek='" + jrek.getText() + "'," +
                    " lokrek='" + lok.getText() + "'," +
                    " judulrek='" + jdrek.getText() + "'," +
                    " tarifrek='" + tbr1.getText() + "'," +
                    " jumpas='" + jml.getText() + "'," +
                    " mulai='" + mul.getSelectedItem() + "'," +
                    " selesai='" + sls.getSelectedItem() + "'" +
                    " where nokartu='" + nokd.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());}
}//GEN-LAST:event_editActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "delete from tb_kdinsidental where nokartu='"+ nokd.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_delActionPerformed

    private void tb_kdatainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_kdatainsMouseClicked
        // TODO add your handling code here:
        int table = tb_kdatains.getSelectedRow();
        //mengambil data dari table
        String a = tb_kdatains.getValueAt(table, 0).toString();
        String b = tb_kdatains.getValueAt(table, 1).toString();
        String c = tb_kdatains.getValueAt(table, 2).toString();
        String d = tb_kdatains.getValueAt(table, 3).toString();
        String e = tb_kdatains.getValueAt(table, 4).toString();
        String f = tb_kdatains.getValueAt(table, 5).toString();
        String g = tb_kdatains.getValueAt(table, 6).toString();
        String h = tb_kdatains.getValueAt(table, 7).toString();
        String i = tb_kdatains.getValueAt(table, 8).toString();
        String j = tb_kdatains.getValueAt(table, 9).toString();
        String k = tb_kdatains.getValueAt(table, 10).toString();
        String l = tb_kdatains.getValueAt(table, 11).toString();
        String m = tb_kdatains.getValueAt(table, 12).toString();
        
        nokd.setText(a);
        npwpd.setSelectedItem(b);
        nmbdn.setText(c);
        almbdn.setText(d);
        nmpml.setText(e);
        almpml.setText(f);
        jrek.setText(g);
        lok.setText(h);
        jdrek.setText(i);
        tbr1.setText(j);
        jml.setText(k);
        mul.setSelectedItem(l);
        sls.setSelectedItem(m);
}//GEN-LAST:event_tb_kdatainsMouseClicked

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mulActionPerformed

    private void npwpdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_npwpdItemStateChanged
        // TODO add your handling code here:
        try{
            Statement stm=c.createStatement();
            r=stm.executeQuery("select * from tb_sptinsidental where npwp_2='"+npwpd.getSelectedItem()+"'");
            while(r.next()){
                jrek.setText(r.getString("jenis"));
                lok.setText(r.getString("lokasi"));
                jdrek.setText(r.getString("judul"));
                tbr1.setText(r.getString("tarif"));
                jml.setText(r.getString("jumlah"));
                mul.setSelectedItem(r.getString("mulai"));
                sls.setSelectedItem(r.getString("selesai"));
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
}//GEN-LAST:event_npwpdItemStateChanged

    private void npwpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npwpdActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_npwpdActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_h3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new kdatainsidental().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almbdn;
    private javax.swing.JTextArea almpml;
    private javax.swing.JButton del;
    private javax.swing.JButton edit;
    private javax.swing.JButton h3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jdrek;
    private javax.swing.JTextField jml;
    private javax.swing.JTextField jrek;
    private javax.swing.JTextField lok;
    private uz.ncipro.calendar.JDateTimePicker mul;
    private javax.swing.JTextField nmbdn;
    private javax.swing.JTextField nmpml;
    private javax.swing.JComboBox nofor;
    private javax.swing.JTextField nokd;
    private javax.swing.JComboBox npwpd;
    private javax.swing.JButton save;
    private uz.ncipro.calendar.JDateTimePicker sls;
    private javax.swing.JTable tb_kdatains;
    private javax.swing.JTextField tbr1;
    private javax.swing.JTextField thn;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
public void bersih(){
nokd.setText("");
nmbdn.setText("");
almbdn.setText("");
nmpml.setText("");
almpml.setText("");
npwpd.setSelectedItem("");
jrek.setText("");
lok.setText("");
jdrek.setText ("");
tbr1.setText ("");
jml.setText ("");
mul.setSelectedItem ("");
sls.setSelectedItem ("");
}

public void tampildata(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nokartu");
tabelnyo.addColumn("nambad");
tabelnyo.addColumn("almbad");
tabelnyo.addColumn("nampem");
tabelnyo.addColumn("almpem");
tabelnyo.addColumn("npw");
tabelnyo.addColumn("jenrek");
tabelnyo.addColumn("lokrek");
tabelnyo.addColumn("judulrek");
tabelnyo.addColumn("tarifrek");
tabelnyo.addColumn("jumpas");
tabelnyo.addColumn("mulrek");
tabelnyo.addColumn("selrek");

try{
koneksi();
String sql = "Select * from tb_kdinsidental order by nokartu asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
});
}
tb_kdatains.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}
