/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lapskpd.java
 *
 * Created on May 22, 2016, 9:27:24 PM
 */
package dispenda;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.lang.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableColumn;
import javax.swing.table.*;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import koneksi.koneksi;
/**
 *
 * @author Agung
 */
public class lapskpd extends javax.swing.JFrame {
Connection c;
JasperReport JasRep;
JasperPrint JasPri;
Map<String, Object> param = new HashMap<String, Object>();
JasperDesign JasDes;
    ResultSet r;
    Statement s; 
 private Statement cn;
    private Connection conn;
    /** Creates new form lapskpd */
    public lapskpd() {
        initComponents();
        tampil();
        lebarKolom();
        koneksi();
    }

public void tampil(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("no_kohir");
tabelnyo.addColumn("npwpd_3");
tabelnyo.addColumn("nama_badan");
tabelnyo.addColumn("alamat_badan");
tabelnyo.addColumn("jatuh_tempo");
tabelnyo.addColumn("jenis");
tabelnyo.addColumn("judul");
tabelnyo.addColumn("lokasi");
tabelnyo.addColumn("tarif");
tabelnyo.addColumn("jumlah");
tabelnyo.addColumn("jumlah2");
tabelnyo.addColumn("ukuran");
tabelnyo.addColumn("ukuran2");
tabelnyo.addColumn("tarif_pajak");
tabelnyo.addColumn("jumlah_bayar");
tabelnyo.addColumn("jumlah_bayar2");
tabelnyo.addColumn("bayar");
tabelnyo.addColumn("bunga");
tabelnyo.addColumn("kenaikan");
tabelnyo.addColumn("total");


try{
koneksi();
String sql = "Select * from tb_skpd order by no_kohir asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
rs.getString(16),
rs.getString(17),
rs.getString(18),
rs.getString(19),
rs.getString(20),
});
}
tb_skp.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_skp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        skp = new javax.swing.JTextField();
        s3 = new javax.swing.JButton();
        p3 = new javax.swing.JButton();
        h5 = new javax.swing.JButton();
        bck4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_skp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_skp);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Laporan Surat Ketetapan Pajak Daerah");

        s3.setBackground(new java.awt.Color(0, 0, 102));
        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/s1.png"))); // NOI18N
        s3.setBorderPainted(false);
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        p3.setBackground(new java.awt.Color(0, 0, 102));
        p3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/p1.png"))); // NOI18N
        p3.setBorderPainted(false);
        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        h5.setBackground(new java.awt.Color(0, 0, 102));
        h5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/h1.png"))); // NOI18N
        h5.setBorderPainted(false);
        h5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h5ActionPerformed(evt);
            }
        });

        bck4.setBackground(new java.awt.Color(0, 0, 102));
        bck4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/b2.png"))); // NOI18N
        bck4.setBorderPainted(false);
        bck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Reklame Permanen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel2)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel3)
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(626, Short.MAX_VALUE)
                .addComponent(skp, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(bck4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 678, Short.MAX_VALUE)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(skp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bck4, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(h5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void h5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h5ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_h5ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("no_kohir");
tabelnyo.addColumn("npwpd_3");
tabelnyo.addColumn("nama_badan");
tabelnyo.addColumn("alamat_badan");
tabelnyo.addColumn("jatuh_tempo");
tabelnyo.addColumn("jenis");
tabelnyo.addColumn("judul");
tabelnyo.addColumn("lokasi");
tabelnyo.addColumn("tarif");
tabelnyo.addColumn("jumlah");
tabelnyo.addColumn("jumlah2");
tabelnyo.addColumn("ukuran");
tabelnyo.addColumn("ukuran2");
tabelnyo.addColumn("tarif_pajak");
tabelnyo.addColumn("jumlah_bayar");
tabelnyo.addColumn("jumlah_bayar2");
tabelnyo.addColumn("bayar");
tabelnyo.addColumn("bunga");
tabelnyo.addColumn("kenaikan");
tabelnyo.addColumn("total");


try {
    koneksi();
    String sql = "select * from tb_skpd where no_kohir like '%"+skp.getText()+"%'";
    ResultSet rs = cn.executeQuery(sql);
    while (rs.next())
    {
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
rs.getString(16),
rs.getString(17),
rs.getString(18),
rs.getString(19),
rs.getString(20),
});
}
            tb_skp.setModel(tabelnyo);
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_s3ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        // TODO add your handling code here:
      try {
            // parameter
            String parameterNama = skp.getText();
                
            //set parameters
            //Map param = new HashMap();
            param.put("no_kohir", parameterNama);
                
            File file = new File("src/Report/skpd.jrxml");
            JasDes = JRXmlLoader.load(file);
            //param.clear();%
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param, conn);
            JasperViewer.viewReport(JasPri, false); 
            
        }catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_p3ActionPerformed

    private void bck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck4ActionPerformed
        // TODO add your handling code here:
        new skpd().setVisible(true);
    }//GEN-LAST:event_bck4ActionPerformed

    public void lebarKolom(){ 
        TableColumn column;
        tb_skp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_skp.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_skp.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_skp.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tb_skp.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_skp.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_skp.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_skp.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = tb_skp.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tb_skp.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tb_skp.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tb_skp.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = tb_skp.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = tb_skp.getColumnModel().getColumn(12); 
        column.setPreferredWidth(250);
        column = tb_skp.getColumnModel().getColumn(13); 
        column.setPreferredWidth(250);
        column = tb_skp.getColumnModel().getColumn(14); 
        column.setPreferredWidth(250);
        column = tb_skp.getColumnModel().getColumn(15); 
        column.setPreferredWidth(150);
        column = tb_skp.getColumnModel().getColumn(16); 
        column.setPreferredWidth(150);
        column = tb_skp.getColumnModel().getColumn(17); 
        column.setPreferredWidth(225);
        column = tb_skp.getColumnModel().getColumn(18); 
        column.setPreferredWidth(250);
        column = tb_skp.getColumnModel().getColumn(19); 
        column.setPreferredWidth(250);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new lapskpd().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck4;
    private javax.swing.JButton h5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton p3;
    private javax.swing.JButton s3;
    private javax.swing.JTextField skp;
    private javax.swing.JTable tb_skp;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
}
