/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lapwp.java
 *
 * Created on Jun 1, 2016, 1:24:36 AM
 */
package dispenda;
import koneksi.koneksi;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener; 
/**
 *
 * @author Agung
 */
public class lapwp extends javax.swing.JFrame {
Connection c;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn;
    /** Creates new form lapwp */
    public lapwp() {
        initComponents();
        tampil();
        lebarKolom();
    }
public void tampil(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("no_formulir");
tabelnyo.addColumn("nama_badan");
tabelnyo.addColumn("alamat_badan");
tabelnyo.addColumn("notelp_badan");
tabelnyo.addColumn("kodpos_badan");
tabelnyo.addColumn("surat_ijin_badan");
tabelnyo.addColumn("nomor_surat");
tabelnyo.addColumn("tgl_badan");
tabelnyo.addColumn("bidang_usaha");
tabelnyo.addColumn("nama_pemilik");
tabelnyo.addColumn("jabatan");
tabelnyo.addColumn("alamat_pemilik");
tabelnyo.addColumn("notelp_pemilik");
tabelnyo.addColumn("kod_pemilik");
tabelnyo.addColumn("kwpjk");
tabelnyo.addColumn("Npwpd");
tabelnyo.addColumn("Npwprd");

try{
koneksi();
String sql = "Select * from tb_wp order by no_formulir asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
rs.getString(16),
rs.getString(17),

});
}
tb_wp.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_wp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        wp = new javax.swing.JTextField();
        s5 = new javax.swing.JButton();
        h6 = new javax.swing.JButton();
        bck1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_wp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_wp);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Data Wajib Pajak Reklame Permanen");

        s5.setBackground(new java.awt.Color(0, 0, 102));
        s5.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\s1.png")); // NOI18N
        s5.setBorderPainted(false);
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        h6.setBackground(new java.awt.Color(0, 0, 102));
        h6.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\h1.png")); // NOI18N
        h6.setBorderPainted(false);
        h6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h6ActionPerformed(evt);
            }
        });

        bck1.setBackground(new java.awt.Color(0, 0, 102));
        bck1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/b2.png"))); // NOI18N
        bck1.setBorderPainted(false);
        bck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(624, Short.MAX_VALUE)
                .addComponent(wp, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bck1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(766, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel2)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(wp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(s5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bck1, 0, 0, Short.MAX_VALUE)
                    .addComponent(h6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void lebarKolom(){ 
        TableColumn column;
        tb_wp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_wp.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_wp.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_wp.getColumnModel().getColumn(2); 
        column.setPreferredWidth(200); 
        column = tb_wp.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_wp.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_wp.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_wp.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = tb_wp.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tb_wp.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tb_wp.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tb_wp.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = tb_wp.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = tb_wp.getColumnModel().getColumn(12); 
        column.setPreferredWidth(250);
        column = tb_wp.getColumnModel().getColumn(13); 
        column.setPreferredWidth(250);
        column = tb_wp.getColumnModel().getColumn(14); 
        column.setPreferredWidth(250);
        column = tb_wp.getColumnModel().getColumn(15); 
        column.setPreferredWidth(250);
        column = tb_wp.getColumnModel().getColumn(16); 
        column.setPreferredWidth(250);
    }
    private void h6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h6ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_h6ActionPerformed

    private void bck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck1ActionPerformed
        // TODO add your handling code here:
        new formFor().setVisible(true);
    }//GEN-LAST:event_bck1ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("no_formulir");
tabelnyo.addColumn("nama_badan");
tabelnyo.addColumn("alamat_badan");
tabelnyo.addColumn("notelp_badan");
tabelnyo.addColumn("kodpos_badan");
tabelnyo.addColumn("surat_ijin_badan");
tabelnyo.addColumn("nomor_surat");
tabelnyo.addColumn("tgl_badan");
tabelnyo.addColumn("bidang_usaha");
tabelnyo.addColumn("nama_pemilik");
tabelnyo.addColumn("jabatan");
tabelnyo.addColumn("alamat_pemilik");
tabelnyo.addColumn("notelp_pemilik");
tabelnyo.addColumn("kod_pemilik");
tabelnyo.addColumn("kwpjk");
tabelnyo.addColumn("Npwpd");
tabelnyo.addColumn("Npwprd");

try{
koneksi();
String sql = "select * from tb_wp where no_formulir like '%"+wp.getText()+"%'";
    ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
rs.getString(16),
rs.getString(17),

});
}
tb_wp.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
    }//GEN-LAST:event_s5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new lapwp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck1;
    private javax.swing.JButton h6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton s5;
    private javax.swing.JTable tb_wp;
    private javax.swing.JTextField wp;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
}
