/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lkdinsidental.java
 *
 * Created on Aug 11, 2016, 10:02:59 PM
 */
package dispenda;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.lang.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableColumn;
import javax.swing.table.*;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import koneksi.koneksi; 
/**
 *
 * @author Agung
 */
public class lkdinsidental extends javax.swing.JFrame {
Connection c;
JasperReport JasRep;
JasperPrint JasPri;
Map<String, Object> param = new HashMap<String, Object>();
JasperDesign JasDes;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn;
    /** Creates new form lkdinsidental */
    public lkdinsidental() {
        initComponents();
        tampil();
        lebarKolom();
        koneksi();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tkdin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        kd = new javax.swing.JTextField();
        s2 = new javax.swing.JButton();
        p2 = new javax.swing.JButton();
        h5 = new javax.swing.JButton();
        bck3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tkdin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tkdin);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Laporan Kartu Data Reklame Insidental");

        s2.setBackground(new java.awt.Color(0, 0, 102));
        s2.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\s1.png")); // NOI18N
        s2.setBorderPainted(false);
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        p2.setBackground(new java.awt.Color(0, 0, 102));
        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/p1.png"))); // NOI18N
        p2.setBorderPainted(false);
        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        h5.setBackground(new java.awt.Color(0, 0, 102));
        h5.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\h1.png")); // NOI18N
        h5.setBorderPainted(false);
        h5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h5ActionPerformed(evt);
            }
        });

        bck3.setBackground(new java.awt.Color(0, 0, 102));
        bck3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/b2.png"))); // NOI18N
        bck3.setBorderPainted(false);
        bck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bck3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(h5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bck3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 680, Short.MAX_VALUE)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel2)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(s2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(kd, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bck3, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(h5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void tampil(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nokartu");
tabelnyo.addColumn("nambad");
tabelnyo.addColumn("almbad");
tabelnyo.addColumn("nampem");
tabelnyo.addColumn("almpem");
tabelnyo.addColumn("npw");
tabelnyo.addColumn("jenrek");
tabelnyo.addColumn("lokrek");
tabelnyo.addColumn("judulrek");
tabelnyo.addColumn("tarifrek");
tabelnyo.addColumn("jumpas");
tabelnyo.addColumn("mulrek");
tabelnyo.addColumn("selrek");

try{
koneksi();
String sql = "Select * from tb_kdinsidental order by nokartu asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
});
}
tkdin.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}

public void lebarKolom(){ 
        TableColumn column;
        tkdin.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tkdin.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tkdin.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tkdin.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tkdin.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tkdin.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tkdin.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tkdin.getColumnModel().getColumn(6); 
        column.setPreferredWidth(250);
        column = tkdin.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tkdin.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tkdin.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tkdin.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = tkdin.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = tkdin.getColumnModel().getColumn(12); 
        column.setPreferredWidth(225);
}
    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nokartu");
tabelnyo.addColumn("nambad");
tabelnyo.addColumn("almbad");
tabelnyo.addColumn("nampem");
tabelnyo.addColumn("almpem");
tabelnyo.addColumn("npw");
tabelnyo.addColumn("jenrek");
tabelnyo.addColumn("lokrek");
tabelnyo.addColumn("judulrek");
tabelnyo.addColumn("tarifrek");
tabelnyo.addColumn("jumpas");
tabelnyo.addColumn("mulrek");
tabelnyo.addColumn("selrek");
        
        try{
            koneksi();
            String sql = "select * from tb_kdinsidental where nokartu like '%"+kd.getText()+"%'";
            ResultSet rs = cn.executeQuery(sql);
            while (rs.next()) {
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
});
}
tkdin.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}//GEN-LAST:event_s2ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        // TODO add your handling code here:
        try {
            // parameter
            String parameterNama = kd.getText();
            
            //set parameters
            //Map param = new HashMap();
            param.put("nokartu", parameterNama);
            
            File file = new File("src/Report/kardatin.jrxml");
            JasDes = JRXmlLoader.load(file);
            //param.clear();%
            JasRep = JasperCompileManager.compileReport(JasDes);
            JasPri = JasperFillManager.fillReport(JasRep, param, conn);
            JasperViewer.viewReport(JasPri, false);
            
        }catch (Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_p2ActionPerformed

    private void h5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h5ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_h5ActionPerformed

    private void bck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bck3ActionPerformed
        // TODO add your handling code here:
        new kdatainsidental().setVisible(true);
}//GEN-LAST:event_bck3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new lkdinsidental().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck3;
    private javax.swing.JButton h5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kd;
    private javax.swing.JButton p2;
    private javax.swing.JButton s2;
    private javax.swing.JTable tkdin;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
}
