/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Log.java
 *
 * Created on Jun 20, 2016, 6:33:00 AM
 */
package dispenda;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Agung
 */
public class Log extends javax.swing.JFrame {

    /** Creates new form Log */
    public Log() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        log = new javax.swing.JButton();
        can = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        jDesktopPane2.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\login3.png")); // NOI18N
        jLabel3.setBounds(0, 0, 380, 70);
        jDesktopPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        usr.setBounds(90, 140, 190, 30);
        jDesktopPane2.add(usr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel1.setText("PASSWORD");
        jLabel1.setBounds(10, 180, 70, 30);
        jDesktopPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12));
        jLabel2.setText("Please fill out the field bellow to start.");
        jLabel2.setBounds(40, 100, 300, 18);
        jDesktopPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 204));

        log.setBackground(new java.awt.Color(0, 0, 204));
        log.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\L1.png")); // NOI18N
        log.setBorderPainted(false);
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        log.setBounds(170, 10, 90, 40);
        jDesktopPane3.add(log, javax.swing.JLayeredPane.DEFAULT_LAYER);

        can.setBackground(new java.awt.Color(0, 0, 204));
        can.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\C1.png")); // NOI18N
        can.setBorderPainted(false);
        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        can.setBounds(280, 10, 90, 40);
        jDesktopPane3.add(can, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(0, 240, 380, 60);
        jDesktopPane2.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\L2.png")); // NOI18N
        jLabel4.setBounds(290, 140, 80, 80);
        jDesktopPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel5.setText("USERNAME");
        jLabel5.setBounds(10, 140, 70, 30);
        jDesktopPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12));
        jLabel6.setText("Welcome to This Aplication ! ");
        jLabel6.setBounds(80, 80, 220, 18);
        jDesktopPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        psw.setBounds(90, 180, 190, 30);
        jDesktopPane2.add(psw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBounds(30, 40, 380, 300);
        jDesktopPane1.add(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
             Connection koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
             ResultSet ds=koneksi.createStatement().executeQuery("select * from tb_admin where username='" +usr.getText()+ "' and password='"+String.valueOf(psw.getPassword())+"'");
             while(ds.next()){
                 menu a= new menu();
                 a.setVisible(true);
                 dispose();
             }
             
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Masukkan User dan Password dengan Benar");
        }
    }//GEN-LAST:event_logActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_canActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Log().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton can;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton log;
    private javax.swing.JPasswordField psw;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
