/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * potensind.java
 *
 * Created on Aug 11, 2016, 10:41:08 PM
 */
package dispenda;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.lang.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.table.TableColumn;
import javax.swing.table.*;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author Agung
 */
public class potensind extends javax.swing.JFrame {
Connection c;
JasperReport JasRep;
JasperPrint JasPri;
Map<String, Object> param = new HashMap<String, Object>();
JasperDesign JasDes;
    ResultSet r;
    Statement s;
    private Statement cn;
    private Connection conn; 
    /** Creates new form potensind */
    public potensind() {
        initComponents();
        tampil1();
        tampil2();
        koneksi();
        lebarKolom();
        lebarKolom2();
        bersih2();
        auto_number();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        nb = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        al = new javax.swing.JTextArea();
        npwp = new javax.swing.JTextField();
        lk = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        br = new javax.swing.JTextArea();
        pj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pot1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        sv = new javax.swing.JButton();
        ed = new javax.swing.JButton();
        de = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_pot2 = new javax.swing.JTable();
        tot = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pr = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 960, 95);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Data Potensi Wajib Pajak Reklame Insidentil");
        jLabel3.setBounds(220, 110, 510, 29);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbActionPerformed(evt);
            }
        });
        nb.setBounds(120, 60, 170, 20);
        jDesktopPane2.add(nb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        al.setColumns(20);
        al.setRows(5);
        jScrollPane2.setViewportView(al);

        jScrollPane2.setBounds(120, 100, 170, 70);
        jDesktopPane2.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        npwp.setBounds(120, 190, 170, 20);
        jDesktopPane2.add(npwp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lk.setBounds(120, 320, 170, 20);
        jDesktopPane2.add(lk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        br.setColumns(20);
        br.setRows(5);
        jScrollPane4.setViewportView(br);

        jScrollPane4.setBounds(120, 230, 170, 70);
        jDesktopPane2.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pj.setBounds(120, 360, 170, 20);
        jDesktopPane2.add(pj, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Alamat");
        jLabel5.setBounds(10, 100, 100, 20);
        jDesktopPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("N P W P D");
        jLabel6.setBounds(10, 190, 100, 20);
        jDesktopPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Bunyi Reklame");
        jLabel7.setBounds(10, 230, 100, 20);
        jDesktopPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Lokasi Reklame");
        jLabel8.setBounds(10, 320, 100, 20);
        jDesktopPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("No Data Potensi");
        jLabel11.setBounds(10, 20, 100, 20);
        jDesktopPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Pajak");
        jLabel15.setBounds(10, 360, 100, 20);
        jDesktopPane2.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        no.setBounds(120, 20, 170, 20);
        jDesktopPane2.add(no, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Nama Badan");
        jLabel13.setBounds(10, 60, 100, 20);
        jDesktopPane2.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBounds(20, 160, 310, 400);
        jDesktopPane1.add(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_pot1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pot1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_pot1);

        jScrollPane1.setBounds(10, 40, 580, 110);
        jDesktopPane4.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Data Wajib Pajak Reklame Insidentil");
        jLabel12.setBounds(180, 10, 200, 20);
        jDesktopPane4.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sv.setBackground(new java.awt.Color(0, 0, 102));
        sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/save.png"))); // NOI18N
        sv.setBorderPainted(false);
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });
        sv.setBounds(30, 10, 60, 59);
        jDesktopPane3.add(sv, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ed.setBackground(new java.awt.Color(0, 0, 102));
        ed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/edit.png"))); // NOI18N
        ed.setBorderPainted(false);
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });
        ed.setBounds(120, 10, 60, 60);
        jDesktopPane3.add(ed, javax.swing.JLayeredPane.DEFAULT_LAYER);

        de.setBackground(new java.awt.Color(0, 0, 102));
        de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/del.png"))); // NOI18N
        de.setBorderPainted(false);
        de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deActionPerformed(evt);
            }
        });
        de.setBounds(210, 10, 60, 60);
        jDesktopPane3.add(de, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(130, 160, 300, 80);
        jDesktopPane4.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Data Potensi Pajak Reklame Insidentil");
        jLabel4.setBounds(180, 240, 210, 20);
        jDesktopPane4.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        tb_pot2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pot2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_pot2);

        jScrollPane3.setBounds(10, 270, 580, 130);
        jDesktopPane4.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tot.setBounds(390, 410, 200, 30);
        jDesktopPane4.add(tot, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("TOTAL KESELURUHAN   Rp");
        jLabel2.setBounds(200, 410, 190, 30);
        jDesktopPane4.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pr.setBackground(new java.awt.Color(204, 204, 204));
        pr.setText("COUNT");
        pr.setBorderPainted(false);
        pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prActionPerformed(evt);
            }
        });
        pr.setBounds(10, 410, 80, 30);
        jDesktopPane4.add(pr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane4.setBounds(340, 160, 600, 460);
        jDesktopPane1.add(jDesktopPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/h1.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(130, 580, 100, 30);
        jDesktopPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void openDataBase() //untuk koneksi dengan data base
{
try
    {
    Class.forName("com.mysql.jdbc.Driver"); c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
    System.out.println("Koneksi Berhasil");
    }   
        catch(ClassNotFoundException e)
        {
            System.out.println("Driver Tidak Ditemukan");
        }
    catch(Exception e)
    {
    System.out.println(e);
    }
}
    
    private void auto_number() {
 try{
        openDataBase();
//Class.forName("com.mysql.jdbc.Driver");
//Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
cn = conn.createStatement();
String SQL = "SELECT max(nod) FROM tb_potensin";


ResultSet rs= cn.executeQuery(SQL);
no.setText("NI0001");
if(rs.next()){
String a=rs.getString(1);
String data[]=a.split("NI");
int x=Integer.parseInt(data[1]);
x=x+1;
String hsl="";
if(x<10){
hsl=data[0].concat("NI").concat("000").concat(Integer.toString(x));
}
else{
hsl=data[0].concat("NI").concat("00").concat(Integer.toString(x));
}
no.setText(hsl);
}
}catch(Exception exc){
System.out.println(exc.getMessage());
}
} 
    
    public void lebarKolom(){ 
        TableColumn column;
        tb_pot1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_pot1.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_pot1.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_pot1.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tb_pot1.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_pot1.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_pot1.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_pot1.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = tb_pot1.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tb_pot1.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tb_pot1.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tb_pot1.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = tb_pot1.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = tb_pot1.getColumnModel().getColumn(12); 
        column.setPreferredWidth(250);
        column = tb_pot1.getColumnModel().getColumn(13); 
        column.setPreferredWidth(250);
        column = tb_pot1.getColumnModel().getColumn(14); 
        column.setPreferredWidth(250);
    }
    
    public void lebarKolom2(){ 
        TableColumn column;
        tb_pot2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_pot2.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_pot2.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_pot2.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tb_pot2.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_pot2.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_pot2.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_pot2.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        
    }
    private void nbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nbActionPerformed

    private void tb_pot1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pot1MouseClicked
        // TODO add your handling code here:
        int table = tb_pot1.getSelectedRow();
        //mengambil data dari table
        String a = tb_pot1.getValueAt(table, 0).toString();
        String b = tb_pot1.getValueAt(table, 1).toString();
        String c = tb_pot1.getValueAt(table, 2).toString();
        String d = tb_pot1.getValueAt(table, 3).toString();
        String e = tb_pot1.getValueAt(table, 4).toString();
        String f = tb_pot1.getValueAt(table, 5).toString();
        String g = tb_pot1.getValueAt(table, 6).toString();
        String h = tb_pot1.getValueAt(table, 7).toString();
        String i = tb_pot1.getValueAt(table, 8).toString();
        String j = tb_pot1.getValueAt(table, 9).toString();
        String k = tb_pot1.getValueAt(table, 10).toString();
        String l = tb_pot1.getValueAt(table, 11).toString();
        String m = tb_pot1.getValueAt(table, 12).toString();
        String n = tb_pot1.getValueAt(table, 13).toString();
        String o = tb_pot1.getValueAt(table, 14).toString();
        
        nb.setText(c);
        al.setText(d);
        npwp.setText(b);
        br.setText(g);
        lk.setText(h);
        pj.setText(o);
}//GEN-LAST:event_tb_pot1MouseClicked

    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "insert into tb_potensin values ('"+ no.getText()+"','"
                    + nb.getText()+"','"
                    + al.getText()+"','"
                    + npwp.getText()+"','"
                    + br.getText()+"','"
                    + lk.getText()+"','"
                    + pj.getText()+"')";
            
            cn.executeUpdate(sql);
            conn.close();
            lebarKolom2();
            tampil2();
            bersih2();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_svActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_potensin set nama='" + nb.getText() + "'," +
                    "alamat='" + al.getText() + "'," +
                    "npwpd='" + npwp.getText() + "'," +
                    "bunyi='" + br.getText() + "'," +
                    "lokasi='" + lk.getText() + "'," +
                    "pajak='" + pj.getText() + "'" +
                    "where nod='" + no.getText() + "'" ;
            
            cn.executeUpdate(sql);
            conn.close();
            lebarKolom2();
            tampil2();
            bersih2();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());}
}//GEN-LAST:event_edActionPerformed

    private void deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "delete from tb_potensin where nod='"+ no.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            lebarKolom2();
            tampil2();
            bersih2();
            
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_deActionPerformed

    private void tb_pot2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pot2MouseClicked
        // TODO add your handling code here:
        int table = tb_pot2.getSelectedRow();
        //mengambil data dari table
        String a = tb_pot2.getValueAt(table, 0).toString();
        String b = tb_pot2.getValueAt(table, 1).toString();
        String c = tb_pot2.getValueAt(table, 2).toString();
        String d = tb_pot2.getValueAt(table, 3).toString();
        String e = tb_pot2.getValueAt(table, 4).toString();
        String f = tb_pot2.getValueAt(table, 5).toString();
        String g = tb_pot2.getValueAt(table, 6).toString();
        
        no.setText(a);
        nb.setText(b);
        al.setText(c);
        npwp.setText(d);
        br.setText(e);
        lk.setText(f);
        pj.setText(g);
}//GEN-LAST:event_tb_pot2MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_jScrollPane3MouseClicked

    private void prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prActionPerformed
        // TODO add your handling code here:
            try {
            koneksi();
       String sql_select = "SELECT SUM(pajak) FROM tb_potensin";
            ResultSet resultSet= cn.executeQuery(sql_select);
       while (resultSet.next()) {
                tot.setText(resultSet.getString(1));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, this.getClass().getName()+ "resultSet"+ e);

        } 
}//GEN-LAST:event_prActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new potensind().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea al;
    private javax.swing.JTextArea br;
    private javax.swing.JButton de;
    private javax.swing.JButton ed;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lk;
    private javax.swing.JTextField nb;
    private javax.swing.JTextField no;
    private javax.swing.JTextField npwp;
    private javax.swing.JTextField pj;
    private javax.swing.JButton pr;
    private javax.swing.JButton sv;
    private javax.swing.JTable tb_pot1;
    private javax.swing.JTable tb_pot2;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}

public void tampil1(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nokohir");
tabelnyo.addColumn("npwp");
tabelnyo.addColumn("nmbad");
tabelnyo.addColumn("albad");
tabelnyo.addColumn("tanggal");
tabelnyo.addColumn("jenis");
tabelnyo.addColumn("judul");
tabelnyo.addColumn("lokasi");
tabelnyo.addColumn("tarif");
tabelnyo.addColumn("jumlah");
tabelnyo.addColumn("pajak");
tabelnyo.addColumn("bayar");
tabelnyo.addColumn("bunga");
tabelnyo.addColumn("naik");
tabelnyo.addColumn("total");


try{
koneksi();
String sql = "Select * from tb_skpinsidental order by nokohir asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
});
}
tb_pot1.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}

public void bersih2(){
no.setText("");
nb.setText("");
al.setText("");
npwp.setText("");
br.setText("");
lk.setText("");
pj.setText("");
}

public void tampil2(){
DefaultTableModel Table = new DefaultTableModel();
Table.addColumn("nod");
Table.addColumn("nama");
Table.addColumn("alamat");
Table.addColumn("npwpd");
Table.addColumn("bunyi");
Table.addColumn("lokasi");
Table.addColumn("pajak");

try{
koneksi();
String sql = "Select * from tb_potensin order by nod asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
    
Table.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
});
}
tb_pot2.setModel(Table);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}
