/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * skpinsidental.java
 *
 * Created on Aug 10, 2016, 10:14:14 PM
 */
package dispenda;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Agung
 */
public class skpinsidental extends javax.swing.JFrame {
Connection c;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn;
    /** Creates new form skpinsidental */
    public skpinsidental() {
       initComponents();
       bersih();
       tampildata(); 
       auto_number();
       lebarKolom();
       tampilnpwp();
    }

    private void openDataBase() //untuk koneksi dengan data base
{
try
    {
    Class.forName("com.mysql.jdbc.Driver"); c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
    System.out.println("Koneksi Berhasil");
    }   
        catch(ClassNotFoundException e)
        {
            System.out.println("Driver Tidak Ditemukan");
        }
    catch(Exception e)
    {
    System.out.println(e);
    }
}  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        abdn = new javax.swing.JTextArea();
        nokhr = new javax.swing.JTextField();
        nmbdn = new javax.swing.JTextField();
        tjt = new uz.ncipro.calendar.JDateTimePicker();
        npwp3 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        knk = new javax.swing.JTextField();
        bng = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        ct2 = new javax.swing.JButton();
        jb = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ctot1 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jen = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jrk = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lks = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jmh = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ct1 = new javax.swing.JButton();
        trpjk = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_skpins = new javax.swing.JTable();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("SURAT KETETAPAN PAJAK DAERAH");

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Nama Badan");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Alamat Badan");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("N P W P D");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("No. Kohir");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Tanggal Jatuh Tempo");

        abdn.setColumns(20);
        abdn.setRows(5);
        jScrollPane2.setViewportView(abdn);

        tjt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10/8/16" }));
        tjt.setDisplayFormat("d/M/yy");

        npwp3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "===== Pilih N P W P D =====" }));
        npwp3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                npwp3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tjt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nmbdn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(nokhr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(npwp3, 0, 221, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nokhr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(npwp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nmbdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tjt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        knk.setBounds(170, 100, 220, 20);
        jDesktopPane1.add(knk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bng.setText("2 %");
        bng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bngActionPerformed(evt);
            }
        });
        bng.setBounds(170, 60, 90, 20);
        jDesktopPane1.add(bng, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Bunga");
        jLabel14.setBounds(10, 60, 36, 15);
        jDesktopPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText("%");
        jLabel20.setBounds(50, 60, 9, 15);
        jDesktopPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Kenaikan");
        jLabel15.setBounds(10, 100, 53, 15);
        jDesktopPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Jumlah Pembayaran (Rp)");
        jLabel13.setBounds(10, 20, 143, 15);
        jDesktopPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tot.setBounds(170, 140, 220, 20);
        jDesktopPane1.add(tot, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ct2.setText("Count 2");
        ct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct2ActionPerformed(evt);
            }
        });
        ct2.setBounds(290, 60, 90, 23);
        jDesktopPane1.add(ct2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jb.setBounds(170, 20, 220, 20);
        jDesktopPane1.add(jb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText("Total Pembayaran (Rp)");
        jLabel26.setBounds(10, 140, 129, 15);
        jDesktopPane1.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ctot1.setText("Count Total");
        ctot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctot1ActionPerformed(evt);
            }
        });
        ctot1.setBounds(170, 170, 100, 30);
        jDesktopPane1.add(ctot1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane2.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenActionPerformed(evt);
            }
        });
        jen.setBounds(160, 20, 243, 20);
        jDesktopPane2.add(jen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Jenis Reklame");
        jLabel17.setBounds(10, 20, 84, 18);
        jDesktopPane2.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jrk.setColumns(20);
        jrk.setRows(5);
        jScrollPane3.setViewportView(jrk);

        jScrollPane3.setBounds(160, 60, 240, 80);
        jDesktopPane2.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Judul Reklame");
        jLabel8.setBounds(10, 60, 84, 15);
        jDesktopPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lks.setBounds(160, 160, 240, 20);
        jDesktopPane2.add(lks, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Lokasi");
        jLabel9.setBounds(10, 160, 38, 15);
        jDesktopPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        tr.setBounds(160, 200, 240, 20);
        jDesktopPane2.add(tr, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Tarif Reklame (Rp)");
        jLabel10.setBounds(10, 200, 105, 15);
        jDesktopPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jmh.setBounds(160, 240, 90, 20);
        jDesktopPane2.add(jmh, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Jumlah Pemasangan");
        jLabel12.setBounds(10, 240, 120, 15);
        jDesktopPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ct1.setText("Count 1");
        ct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct1ActionPerformed(evt);
            }
        });
        ct1.setBounds(160, 320, 90, 23);
        jDesktopPane2.add(ct1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        trpjk.setText("25 %");
        trpjk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trpjkActionPerformed(evt);
            }
        });
        trpjk.setBounds(160, 280, 90, 20);
        jDesktopPane2.add(trpjk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Tarif Pajak");
        jLabel16.setBounds(10, 280, 61, 15);
        jDesktopPane2.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText("%");
        jLabel22.setBounds(80, 280, 9, 15);
        jDesktopPane2.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_skpins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_skpins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_skpinsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb_skpins);

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\save.png")); // NOI18N
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\edit.png")); // NOI18N
        edit.setBorderPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 0, 102));
        delete.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\del.png")); // NOI18N
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save)
                    .addComponent(delete)
                    .addComponent(edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        h1.setBackground(new java.awt.Color(0, 0, 102));
        h1.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\h1.png")); // NOI18N
        h1.setBorderPainted(false);
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(393, 393, 393))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel27.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 0));
        jLabel27.setText("REKLAME INSIDENTIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(248, 248, 248))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane5.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilnpwp(){
        try {
            
            Statement statement = (Statement) c.createStatement();  
            String sql = "SELECT * FROM tb_kdinsidental";
            ResultSet resultSet = statement.executeQuery(sql);
            
            while(resultSet.next()){
            npwp3.addItem(resultSet.getString("npw"));
            }
            
            resultSet.close();
            statement.close();
            
            System.out.println("Tampil Data Berhasil");
        }   catch (SQLException ex) {
            System.out.println("Tampil Data Gagal \n Pesan :" + ex.toString());
        }
}

    private void auto_number() {
try{
    openDataBase();
//Class.forName("com.mysql.jdbc.Driver");
//Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
cn = conn.createStatement();
String SQL = "SELECT max(nokohir) FROM tb_skpinsidental";
ResultSet rs= cn.executeQuery(SQL);
nokhr.setText("NKI0001");
if(rs.next()){
String a=rs.getString(1);
String data[]=a.split("NKI");
int x=Integer.parseInt(data[1]);
x=x+1;
String hsl="";
if(x<10){
hsl=data[0].concat("NKI").concat("000").concat(Integer.toString(x));
}
else{
hsl=data[0].concat("NKI").concat("00").concat(Integer.toString(x));
}
nokhr.setText(hsl);
}
}catch(Exception exc){
System.out.println(exc.getMessage());
}
} 
    private void npwp3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_npwp3ItemStateChanged
        // TODO add your handling code here:
        try{
            Statement stm=c.createStatement();
            r=stm.executeQuery("select * from tb_kdinsidental where npw='"+npwp3.getSelectedItem()+"'");
            while(r.next()){
                nmbdn.setText(r.getString("namabad"));
                abdn.setText(r.getString("almbad"));
                jen.setText(r.getString("jenrek"));
                jrk.setText(r.getString("judulrek"));
                lks.setText(r.getString("lokrek"));
                tr.setText(r.getString("tarifrek"));
                jmh.setText(r.getString("jumpas"));
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
}//GEN-LAST:event_npwp3ItemStateChanged

    private void bngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bngActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_bngActionPerformed

    private void ct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct2ActionPerformed
        // TODO add your handling code here:
        float b1=Float.parseFloat(jb.getText());
        float tt1=b1*2/100;
        knk.setText(String.valueOf(tt1));
}//GEN-LAST:event_ct2ActionPerformed

    private void ctot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctot1ActionPerformed
        // TODO add your handling code here:
        float c1=Float.parseFloat(jb.getText());
        float c2=Float.parseFloat(knk.getText());
        float t1=c1+c2;
        tot.setText(String.valueOf(t1));
}//GEN-LAST:event_ctot1ActionPerformed

    private void jenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jenActionPerformed

    private void ct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct1ActionPerformed
        // TODO add your handling code here:
        float c1=Float.parseFloat(tr.getText());
        float c2=Float.parseFloat(jmh.getText());
        float tt=(c1*c2)*25/100;
        jb.setText(String.valueOf(tt));
}//GEN-LAST:event_ct1ActionPerformed

    private void trpjkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trpjkActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_trpjkActionPerformed

    private void tb_skpinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_skpinsMouseClicked
        // TODO add your handling code here:
        int table = tb_skpins.getSelectedRow();
        //mengambil data dari table
        String a = tb_skpins.getValueAt(table, 0).toString();
        String b = tb_skpins.getValueAt(table, 1).toString();
        String c = tb_skpins.getValueAt(table, 2).toString();
        String d = tb_skpins.getValueAt(table, 3).toString();
        String e = tb_skpins.getValueAt(table, 4).toString();
        String f = tb_skpins.getValueAt(table, 5).toString();
        String g = tb_skpins.getValueAt(table, 6).toString();
        String h = tb_skpins.getValueAt(table, 7).toString();
        String i = tb_skpins.getValueAt(table, 8).toString();
        String j = tb_skpins.getValueAt(table, 9).toString();
        String k = tb_skpins.getValueAt(table, 10).toString();
        String l = tb_skpins.getValueAt(table, 11).toString();
        String m = tb_skpins.getValueAt(table, 12).toString();
        String n = tb_skpins.getValueAt(table, 13).toString();
        String o = tb_skpins.getValueAt(table, 14).toString();
        
        nokhr.setText(a);
        npwp3.setSelectedItem(b);
        nmbdn.setText(c);
        abdn.setText(d);
        tjt.setSelectedItem(e);
        jen.setText(f);
        jrk.setText(g);
        lks.setText(h);
        tr.setText(i);
        jmh.setText(j);
        trpjk.setText(k);
        jb.setText(l);
        bng.setText(m);
        knk.setText(n);
        tot.setText(o);
}//GEN-LAST:event_tb_skpinsMouseClicked

    public void lebarKolom(){ 
        TableColumn column;
        tb_skpins.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_skpins.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_skpins.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_skpins.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tb_skpins.getColumnModel().getColumn(3); 
        column.setPreferredWidth(175);
        column = tb_skpins.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_skpins.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_skpins.getColumnModel().getColumn(6); 
        column.setPreferredWidth(100);
        column = tb_skpins.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
        column = tb_skpins.getColumnModel().getColumn(8); 
        column.setPreferredWidth(175);
        column = tb_skpins.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tb_skpins.getColumnModel().getColumn(10); 
        column.setPreferredWidth(150);
        column = tb_skpins.getColumnModel().getColumn(11); 
        column.setPreferredWidth(225);
        column = tb_skpins.getColumnModel().getColumn(12); 
        column.setPreferredWidth(250);
        column = tb_skpins.getColumnModel().getColumn(13); 
        column.setPreferredWidth(250);
        column = tb_skpins.getColumnModel().getColumn(14); 
        column.setPreferredWidth(250);
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            
            koneksi();
            String sql = "insert into tb_skpinsidental values ('"+ nokhr.getText()+"',"
                    + "'"+ npwp3.getSelectedItem()+"',"
                    + "'" + nmbdn.getText() +"',"
                    + "'" + abdn.getText()+"',"
                    + "'" + tjt.getSelectedItem() +"',"
                    + "'" + jen.getText() +"',"
                    + "'" + jrk.getText() +"',"
                    + "'" + lks.getText() + "',"
                    + "'" + tr.getText() + "',"
                    + "'" + jmh.getText() + "',"
                    + "'" + trpjk.getText() + "',"
                    + "'" + jb.getText() + "',"
                    + "'" + bng.getText() + "',"
                    + "'" + knk.getText() + "',"
                    + "'" + tot.getText() + "')";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_skpinsidental set npwp='" + npwp3.getSelectedItem() + "'," +
                    " nmbad='" + nmbdn.getText() + "'," +
                    " albad='" + abdn.getText() + "'," +
                    " tanggal='" + tjt.getSelectedItem() + "'," +
                    " jenis='" + jen.getText() + "'," +
                    " judul='" + jrk.getText() + "'," +
                    " lokasi='" + lks.getText() + "'," +
                    " tarif='" + tr.getText() + "'," +
                    " jumlah='" + jmh.getText() + "'," +
                    " pajak='" + trpjk.getText() + "'," +
                    " bayar='" + jb.getText() + "'," +
                    " bunga='" + bng.getText() + "'," +
                    " naik='" + knk.getText() + "'," +
                    " total='" + tot.getText() + "'" +
                    " where nokohir='" + nokhr.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());}
}//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "delete from tb_skpinsidental where nokohir='"+ nokhr.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_deleteActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_h1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new skpinsidental().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea abdn;
    private javax.swing.JTextField bng;
    private javax.swing.JButton ct1;
    private javax.swing.JButton ct2;
    private javax.swing.JButton ctot1;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton h1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jb;
    private javax.swing.JTextField jen;
    private javax.swing.JTextField jmh;
    private javax.swing.JTextArea jrk;
    private javax.swing.JTextField knk;
    private javax.swing.JTextField lks;
    private javax.swing.JTextField nmbdn;
    private javax.swing.JTextField nokhr;
    private javax.swing.JComboBox npwp3;
    private javax.swing.JButton save;
    private javax.swing.JTable tb_skpins;
    private uz.ncipro.calendar.JDateTimePicker tjt;
    private javax.swing.JTextField tot;
    private javax.swing.JTextField tr;
    private javax.swing.JTextField trpjk;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
public void bersih(){
nokhr.setText("");
npwp3.setSelectedItem("");
nmbdn.setText("");
abdn.setText("");
tjt.setSelectedItem("");
jen.setText("");
jrk.setText("");
lks.setText("");
tr.setText ("");
jmh.setText ("");
jb.setText ("");
knk.setText ("");
tot.setText ("");
}

public void tampildata(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nokohir");
tabelnyo.addColumn("npwp");
tabelnyo.addColumn("nmbad");
tabelnyo.addColumn("albad");
tabelnyo.addColumn("tanggal");
tabelnyo.addColumn("jenis");
tabelnyo.addColumn("judul");
tabelnyo.addColumn("lokasi");
tabelnyo.addColumn("tarif");
tabelnyo.addColumn("jumlah");
tabelnyo.addColumn("pajak");
tabelnyo.addColumn("bayar");
tabelnyo.addColumn("bunga");
tabelnyo.addColumn("naik");
tabelnyo.addColumn("total");


try{
koneksi();
String sql = "Select * from tb_skpinsidental order by nokohir asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
rs.getString(9),
rs.getString(10),
rs.getString(11),
rs.getString(12),
rs.getString(13),
rs.getString(14),
rs.getString(15),
});
}
tb_skpins.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}
