/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tbinsidental.java
 *
 * Created on Aug 11, 2016, 12:20:07 AM
 */
package dispenda;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Agung
 */
public class tbinsidental extends javax.swing.JFrame {
Connection c;
    ResultSet r;
    Statement s;
 private Statement cn;
    private Connection conn;
    /** Creates new form tbinsidental */
    public tbinsidental() {
        initComponents();
        bersih();
        tampildata(); 
        lebarKolom();
        auto_number();
        tampilnpwpd(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        nb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        td = new uz.ncipro.calendar.JDateTimePicker();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        al = new javax.swing.JTextArea();
        npwp4 = new javax.swing.JComboBox();
        nmbd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sp = new javax.swing.JTextArea();
        kr = new javax.swing.JTextField();
        jlh = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_tbins = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 0));
        nb.setBounds(160, 180, 210, 20);
        jDesktopPane1.add(nb, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Tanggal Diterima");
        jLabel4.setBounds(630, 180, 100, 14);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Nomor Bukti");
        jLabel6.setBounds(70, 180, 70, 14);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("REKLAME INSIDENTIL");
        jLabel9.setBounds(370, 130, 270, 29);
        jDesktopPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        td.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "11/8/16" }));
        td.setDisplayFormat("d/M/yy");
        td.setBounds(760, 180, 140, 20);
        jDesktopPane1.add(td, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Alamat Badan");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("NPWPD");

        al.setColumns(20);
        al.setRows(5);
        jScrollPane1.setViewportView(al);

        npwp4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "===== Pilih N P W P D =====" }));
        npwp4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                npwp4ItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Nama Badan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(npwp4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nmbd, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(npwp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nmbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel1.setBounds(40, 30, 400, 210);
        jDesktopPane3.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Sebagai Pembayaran");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Kode Rekening");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11));
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Jumlah (Rp)");

        sp.setColumns(20);
        sp.setRows(5);
        jScrollPane2.setViewportView(sp);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(kr)
                    .addComponent(jlh))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(18, 88, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBounds(470, 30, 420, 210);
        jDesktopPane3.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tb_tbins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_tbins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_tbinsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_tbins);

        jDesktopPane2.setBackground(new java.awt.Color(0, 0, 102));
        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        save.setBackground(new java.awt.Color(0, 0, 102));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/save.png"))); // NOI18N
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.setBounds(20, 30, 50, 50);
        jDesktopPane2.add(save, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edit.setBackground(new java.awt.Color(0, 0, 102));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/edit.png"))); // NOI18N
        edit.setBorderPainted(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        edit.setBounds(100, 30, 50, 50);
        jDesktopPane2.add(edit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        delete.setBackground(new java.awt.Color(0, 0, 102));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/del.png"))); // NOI18N
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete.setBounds(180, 30, 50, 50);
        jDesktopPane2.add(delete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel3.setBounds(40, 260, 850, 190);
        jDesktopPane3.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        h1.setBackground(new java.awt.Color(0, 0, 102));
        h1.setIcon(new javax.swing.ImageIcon("E:\\Angger\\KULIAH\\Gambar Icon\\h1.png")); // NOI18N
        h1.setBorderPainted(false);
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        h1.setBounds(410, 460, 90, 30);
        jDesktopPane3.add(h1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDesktopPane3.setBounds(20, 210, 920, 500);
        jDesktopPane1.add(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dispenda/KOP.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 960, 100);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("TANDA BUKTI PEMBAYARAN PAJAK DAERAH");
        jLabel10.setBounds(240, 100, 540, 29);
        jDesktopPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openDataBase() //untuk koneksi dengan data base
{
try
    {
    Class.forName("com.mysql.jdbc.Driver"); c=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
    System.out.println("Koneksi Berhasil");
    }   
        catch(ClassNotFoundException e)
        {
            System.out.println("Driver Tidak Ditemukan");
        }
    catch(Exception e)
    {
    System.out.println(e);
    }
}  

public void tampilnpwpd(){
        try {
            
            Statement statement = (Statement) c.createStatement();  
            String sql = "SELECT * FROM tb_skpinsidental";
            ResultSet resultSet = statement.executeQuery(sql);
            
            while(resultSet.next()){
                npwp4.addItem(resultSet.getString("npwp"));
            }
            
            resultSet.close();
            statement.close();
            
            System.out.println("Tampil Data Berhasil");
        }   catch (SQLException ex) {
            System.out.println("Tampil Data Gagal \n Pesan :" + ex.toString());
        }
}

    private void auto_number() {
try{
    openDataBase();
//Class.forName("com.mysql.jdbc.Driver");
//Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
cn = conn.createStatement();
String SQL = "SELECT max(nobukti) FROM tb_tbinsidental";
ResultSet rs= cn.executeQuery(SQL);
nb.setText("NBI0001");
if(rs.next()){
String a=rs.getString(1);
String data[]=a.split("NBI");
int x=Integer.parseInt(data[1]);
x=x+1;
String hsl="";
if(x<10){
hsl=data[0].concat("NBI").concat("000").concat(Integer.toString(x));
}
else{
hsl=data[0].concat("NBI").concat("00").concat(Integer.toString(x));
}
nb.setText(hsl);
}
}catch(Exception exc){
System.out.println(exc.getMessage());
}
} 
    private void npwp4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_npwp4ItemStateChanged
        // TODO add your handling code here:
        try{
            Statement stm=c.createStatement();
            r=stm.executeQuery("select * from tb_skpinsidental where npwp='"+npwp4.getSelectedItem()+"'");
            while(r.next()){
                nmbd.setText(r.getString("nmbad"));
                al.setText(r.getString("albad"));
                jlh.setText(r.getString("total"));
            }
        }
        
        catch(Exception e){
            e.printStackTrace();
        }
}//GEN-LAST:event_npwp4ItemStateChanged

    private void tb_tbinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_tbinsMouseClicked
        // TODO add your handling code here:
        int table = tb_tbins.getSelectedRow();
        //mengambil data dari table
        String a = tb_tbins.getValueAt(table, 0).toString();
        String b = tb_tbins.getValueAt(table, 1).toString();
        String c = tb_tbins.getValueAt(table, 2).toString();
        String d = tb_tbins.getValueAt(table, 3).toString();
        String e = tb_tbins.getValueAt(table, 4).toString();
        String f = tb_tbins.getValueAt(table, 5).toString();
        String g = tb_tbins.getValueAt(table, 6).toString();
        String h = tb_tbins.getValueAt(table, 7).toString();
        
        nb.setText(a);
        td.setSelectedItem(b);
        npwp4.setSelectedItem(c);
        nmbd.setText(d);
        al.setText(e);
        sp.setText(f);
        kr.setText(g);
        jlh.setText(h);
}//GEN-LAST:event_tb_tbinsMouseClicked

    public void lebarKolom(){ 
        TableColumn column;
        tb_tbins.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tb_tbins.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tb_tbins.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tb_tbins.getColumnModel().getColumn(2); 
        column.setPreferredWidth(200); 
        column = tb_tbins.getColumnModel().getColumn(3); 
        column.setPreferredWidth(200);
        column = tb_tbins.getColumnModel().getColumn(4); 
        column.setPreferredWidth(200);
        column = tb_tbins.getColumnModel().getColumn(5); 
        column.setPreferredWidth(175);
        column = tb_tbins.getColumnModel().getColumn(6); 
        column.setPreferredWidth(150);
        column = tb_tbins.getColumnModel().getColumn(7); 
        column.setPreferredWidth(190);
    }
    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        try{
            
            koneksi();
            String sql = "insert into tb_tbinsidental values ('"+ nb.getText()+"',"
                    + "'"+ td.getSelectedItem()+"',"
                    + "'" + npwp4.getSelectedItem() +"',"
                    + "'" + nmbd.getText() +"',"
                    + "'" + al.getText() +"', "
                    + "'" + sp.getText() +"',"
                    + "'" + kr.getText() + "',"
                    + "'" + jlh.getText() + "')";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses penyimpanan gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_saveActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "update tb_tbinsidental set tanggal='" + td.getSelectedItem() + "'," +
                    " npwpd='" + npwp4.getSelectedItem() + "'," +
                    " nama='" + nmbd.getText() + "'," +
                    " alamat='" + al.getText() + "'," +
                    " pembayaran='" + sp.getText() + "'," +
                    " koderek='" + kr.getText() + "'," +
                    " bayar='" + jlh.getText() + "'" +
                    " where nobukti='" + nb.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di rubah");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());}
}//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            koneksi();
            String sql = "delete from tb_tbinsidental where nobukti='"+ nb.getText() +"'";
            cn.executeUpdate(sql);
            conn.close();
            
            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_deleteActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_h1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new tbinsidental().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea al;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton h1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jlh;
    private javax.swing.JTextField kr;
    private javax.swing.JTextField nb;
    private javax.swing.JTextField nmbd;
    private javax.swing.JComboBox npwp4;
    private javax.swing.JButton save;
    private javax.swing.JTextArea sp;
    private javax.swing.JTable tb_tbins;
    private uz.ncipro.calendar.JDateTimePicker td;
    // End of variables declaration//GEN-END:variables
public void koneksi(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dispenda","root","");
        cn = conn.createStatement();
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
}
public void bersih(){
nb.setText("");
td.setSelectedItem("");
npwp4.setSelectedItem("");
nmbd.setText("");
al.setText("");
sp.setText("");
kr.setText("");
jlh.setText ("");
}

public void tampildata(){
DefaultTableModel tabelnyo = new DefaultTableModel();
tabelnyo.addColumn("nobukti");
tabelnyo.addColumn("tanggal");
tabelnyo.addColumn("npwpd");
tabelnyo.addColumn("nama");
tabelnyo.addColumn("alamat");
tabelnyo.addColumn("pembayaran");
tabelnyo.addColumn("koderek");
tabelnyo.addColumn("bayar");

try{
koneksi();
String sql = "Select * from tb_tbinsidental order by nobukti asc";
ResultSet rs = cn.executeQuery(sql);
while (rs.next())
{
tabelnyo.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
});
}
tb_tbins.setModel(tabelnyo);

}catch (Exception e){
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
}
}
}
